[package]
name = "rustyfill-test-allocator"
version.workspace = true
edition = "2024"
description = "Test-time global allocator for injecting OOM conditions"

[dependencies]
static_assertions = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = { workspace = true }
rustyfill = { workspace = true }
