[package]
name = "rustyfill-test-allocator"
version = "0.1.0"
edition = "2024"
description = "Test-time global allocator for injecting OOM conditions"

[dependencies]
static_assertions = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = { workspace = true }
rustyfill = { path = "../rustyfill" }
