[workspace]
members = ["rustyfill", "rustyfill-macros", "xtask"]
resolver = "2"

[workspace.dependencies]
dashmap = { version = "6", features = ["raw-api"] }
hashbrown = "0.14.5"
libc = "0.2.189"
once_cell = "1.21.4"
rustversion = "1.0.23"
rustyfill-macros = { path = "rustyfill-macros" }
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
no-panic = "0.1.37"
static_assertions = "1.1"
cargo-build = "1.0.0"
moto-rt = { version = "0.16", features = ["rustc-dep-of-std"] }
hermit-abi = { version = "0.5.0", features = ["rustc-dep-of-std"] }
wasip1 = { version = "1.0.0", features = ["rustc-dep-of-std"], default-features = false }
wasip2 = { version = "1.0.3", features = ["rustc-dep-of-std"], default-features = false }
wasip3 = { version = "0.7.0", features = ["rustc-dep-of-std"], default-features = false }
r-efi = { version = "5.2.0", features = ["rustc-dep-of-std"] }
r-efi-alloc = { version = "2.0.0", features = ["rustc-dep-of-std"] }

[profile.dev]
opt-level = 2
