//! [autogenerated by LLM] Internal implementation of the `try_format_args!` proc-macro.
//!
//! # Overview
//!
//! This module transforms a `format_args!`-style invocation into an equivalent
//! `core::fmt::Arguments` value where every argument that will be formatted is
//! wrapped in the appropriate wrapper type (`TryDebugWrapper`, `TryDisplayWrapper`,
//! `TryLowerHexWrapper`, or `TryUpperHexWrapper`). Arguments that are only used as
//! numeric width or precision specifiers (e.g., `"{val:<width$}"`) are passed
//! through unwrapped, since those positions expect raw integer values.
//!
//! Each wrapper carries a hard bound on its type parameter (e.g., `T: TryDebug`),
//! so the compiler produces precise diagnostics when a value lacks the expected trait.
//!
//! The pipeline has three phases:
//!
//! 1. **Parsing** — `TryFormatArgsInput::parse()` extracts the format string literal
//!    and splits remaining tokens on top-level commas into individual arguments,
//!    detecting named bindings (`name = expr`) vs positional args.
//!
//! 2. **Analysis** — `analyze_format_string()` walks the format string character-by-character
//!    to build a `FormatAnalysis` AST. For each `{...}` placeholder it determines:
//!    - Which argument slot it references (positional index, name, or auto-nexting).
//!    - Which formatting trait the placeholder requires (`Debug`, `Display`, `LowerHex`,
//!      `UpperHex`) based on the trailing format character.
//!    - Whether the slot supplies a numeric measure like dynamic width/precision
//!      (`WrapKind::Measure`).
//!    - Slots used for both display and measure retain their display wrapper kind.
//!
//! 3. **Emission** — `emit()` iterates the parsed arguments, looks up each one's usage
//!    in the analysis, and wraps it in the corresponding `*Wrapper::new()` call.
//!    The final output is a single `core::format_args!(...)` call with selectively-wrapped
//!    arguments.
//!
//! # Format Spec AST Generation Detail
//!
//! The "AST" is not a tree of nodes but a flat map from argument indices/names to their
//! `WrapKind` classification, produced by `analyze_format_string()`. Here is how it works:
//!
//! ## Character-by-character scan
//!
//! `analyze_format_string()` creates a `Peekable<char>` iterator over the format string
//! and processes it left-to-right:
//!
//! - A lone `{` begins a placeholder. An escaped `{{` is skipped (literal brace).
//! - Inside a placeholder, `parse_arg_spec()` reads the argument reference:
//!   - ASCII digit(s) → `ArgKind::Positional(idx)`
//!   - Alphanumeric identifier → `ArgKind::Named(name)`
//!   - Anything else (`:`, `}`, or EOF) → `ArgKind::Auto` (auto-nexting)
//! - If `ArgKind::Auto` is seen anywhere, `has_auto` is set to `true`. When emitting,
//!   this forces all unnamed arguments to be treated as `Display` (since we cannot
//!   statically determine which auto-slot maps to which arg at macro-expand time).
//!
//! ## Format spec parsing (after `:`)
//!
//! If the placeholder contains a `:`, `parse_format_spec()` consumes the remainder
//! of the spec in order:
//!
//! 1. **Alignment**: optional `<`, `>`, `^`, or `=`
//! 2. **Sign**: optional `+`, `-`, or ` `
//! 3. **Alternate flag**: optional `#`
//! 4. **Zero-padding**: optional `0`
//! 5. **Width**: delegated to `parse_width_or_precision()`
//! 6. **Precision**: if `.` is present, consume it and delegate again to `parse_width_or_precision()`
//! 7. **Trailing format char**: a single non-`}` character (e.g., `?`, `x`, `X`, `o`, `b`)
//!
//! The trailing format char determines the wrapper kind:
//! - `?` → `WrapKind::Debug`
//! - `x` → `WrapKind::LowerHex`
//! - `X` → `WrapKind::UpperHex`
//! - anything else (including none) → `WrapKind::Display`
//!
//! ### Dynamic width / precision detection
//!
//! `parse_width_or_precision()` handles three cases:
//!
//! - `*` — static star-width, no argument consumed from our list (handled by the
//!   compiler's own formatting machinery via positional `*` args).
//! - Digit sequence followed by `$` — e.g., `{0$}` or `10$`. The digit sequence is
//!   parsed as a usize index, and that slot is recorded as `WrapKind::Measure` because
//!   it supplies a numeric width/precision value, not displayed content.
//! - Identifier followed by `$` — e.g., `{w$}`. The identifier is extracted and
//!   registered as `WrapKind::Measure` in the `named` map.
//!
//! Plain digit sequences without `$` are just literal widths (e.g., `{:.5}`) and do
//! not reference any argument slot.
//!
//! ## Usage merging
//!
//! `merge_kind_p()` (positional) and `merge_kind_n()` (named) combine multiple
//! usages of the same slot. If a slot appears both as a display target and as a
//! width/precision specifier, it retains its display wrapper kind (the value IS
//! displayed, so it needs wrapping). If a slot is used with different format traits
//! across placeholders, it becomes `WrapKind::Multi` — emission falls back to
//! `TryDisplayWrapper` as the safest common denominator.
//!
//! # Why manual tokenization instead of syn?
//!
//! The parser uses raw `proc_macro2::TokenTree` iteration rather than `syn::parse`
//! because format macro inputs can contain arbitrary Rust expressions that may not
//! parse cleanly as a single `syn` type (e.g., trailing commas, mixed named/positional
//! args). Manual comma-splitting at depth 0 preserves the original token streams
//! faithfully for re-emission into `core::format_args!`.

use proc_macro::TokenStream;
use quote::{ToTokens, quote};
use std::collections::BTreeMap;

/// Entry point for the `try_format_args!` proc-macro.
///
/// [autogenerated by LLM] Parses the input tokens, analyzes which arguments need
/// `TryFmt` wrapping based on their role in the format string, and emits a
/// `core::format_args!()` call with selectively-wrapped arguments.
///
/// On parse failure, returns a `compile_error!` so the user sees a clear diagnostic
/// at the call site.
pub(crate) fn try_format_args(input: TokenStream) -> TokenStream {
    match TryFormatArgsInput::parse(input.clone()) {
        Ok(result) => result.emit().into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// [autogenerated by LLM] Intermediate representation after parsing macro input.
///
/// Holds the format string literal (as a plain `String` for analysis) and the list
/// of arguments as `(option_name, token_stream)` pairs. A `Some(name)` indicates a
/// named binding (e.g., `foo = some_expr`), while `None` means a positional argument.
///
/// The token stream for each argument is preserved exactly as written by the caller,
/// so that re-emitting it produces semantically identical code.
struct TryFormatArgsInput {
    /// The raw contents of the format string literal (without quotes).
    format_string: String,
    /// The original literal token, preserved so we can re-emit it with its
    /// source span intact for IDE highlighting.
    format_literal: proc_macro2::TokenTree,
    /// Parsed arguments: `(binding_name_if_named, expression_tokens)`.
    args: Vec<(Option<String>, proc_macro2::TokenStream)>,
}

/// [autogenerated by LLM] Describes which wrapper type an argument slot needs.
///
/// Each variant maps to a specific wrapper struct whose constructor enforces the
/// corresponding trait bound at compile time:
///
/// - `Debug` → `TryDebugWrapper<T: TryDebug>` — emitted for `{:?}` placeholders.
/// - `Display` → `TryDisplayWrapper<T: TryDisplay>` — emitted for `{}`, `{:#}`, `{:+}`, etc.
/// - `LowerHex` → `TryLowerHexWrapper<T: TryLowerHex>` — emitted for `{:x}` / `{:#x}`.
/// - `UpperHex` → `TryUpperHexWrapper<T: TryUpperHex>` — emitted for `{:X}` / `{:#X}`.
/// - `Measure` — the slot only supplies a numeric width/precision value; no wrapper needed.
/// - `Multi` — the slot is used with multiple conflicting format traits across
///   placeholders. Falls back to `Display` during emission as the safest default.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum WrapKind {
    Debug,
    Display,
    LowerHex,
    UpperHex,
    LowerExp,
    UpperExp,
    Measure,
    Multi,
}

impl WrapKind {
    /// [autogenerated by LLM] Merge two wrapper kinds for the same slot.
    ///
    /// - Any display kind + `Measure` → keeps the display kind (still needs wrapping).
    /// - Same kind + same kind → unchanged.
    /// - Different display kinds → `Multi` (conflict, falls back to Display at emit).
    /// - `Measure` + `Measure` → `Measure`.
    fn merge(self, other: Self) -> Self {
        match (self, other) {
            // Same kind is idempotent
            (a, b) if a == b => a,
            // Measure is absorbed by any display kind
            (WrapKind::Measure, d) | (d, WrapKind::Measure) => d,
            // Conflicting display kinds or anything else → Multi
            _ => WrapKind::Multi,
        }
    }
}

impl TryFormatArgsInput {
    /// [autogenerated by LLM] Phase 1 — Parse raw macro input into IR.
    ///
    /// Converts the incoming `TokenStream` into a `TryFormatArgsInput` struct
    /// containing the format string and a list of arguments.
    ///
    /// ## Algorithm
    ///
    /// 1. Convert `proc_macro::TokenStream` → `proc_macro2::TokenStream` → `Vec<TokenTree>`.
    /// 2. Assert that the first token is a string literal. Parse it as `syn::LitStr`
    ///    and extract its `.value()` (the unescaped string contents). This becomes
    ///    `format_string`, used later by `analyze_format_string()` to determine
    ///    which argument slots need wrapping.
    /// 3. Iterate remaining tokens left-to-right, skipping top-level commas.
    ///    For each non-comma segment, call `collect_arg_trees()` to gather all
    ///    tokens belonging to one argument (respecting grouping depth so that
    ///    commas inside `{}`, `()`, `[]` don't terminate early).
    /// 4. Pass each argument's token stream to `parse_arg()` which detects whether
    ///    it has the form `ident = expr` (a named binding). If so, extracts the
    ///    identifier name and returns only the expression portion via `split_after_eq()`.
    /// 5. Push `(option_name, expr_tokens)` into the `args` vector.
    ///
    /// ## Why not use `syn`?
    ///
    /// Format macro inputs are intentionally loose: they allow trailing commas,
    /// mixed named/positional syntax, and arbitrary expressions. A single `syn`
    /// type cannot represent this flexibility. Manual tokenization at depth 0
    /// preserves fidelity while remaining simple.
    fn parse(input: TokenStream) -> syn::Result<Self> {
        let tokens: proc_macro2::TokenStream = input.into();
        let tts: Vec<proc_macro2::TokenTree> = tokens.clone().into_iter().collect();
        let mut pos = 0;

        // First token must be a string literal.
        if pos >= tts.len() {
            return Err(syn::Error::new_spanned(
                tokens,
                "expected format string literal",
            ));
        }

        let (format_string, format_literal) =
            if let proc_macro2::TokenTree::Literal(ref lit) = tts[pos] {
                let lit_str: syn::LitStr = syn::parse2(lit.to_token_stream()).map_err(|_| {
                    syn::Error::new_spanned(lit.to_token_stream(), "expected a string literal")
                })?;
                pos += 1;
                (lit_str.value(), tts[pos - 1].clone())
            } else {
                return Err(syn::Error::new_spanned(
                    tts[pos].to_token_stream(),
                    "expected a string literal",
                ));
            };

        let mut args = Vec::new();

        while pos < tts.len() {
            // Skip commas
            if matches!(tts[pos], proc_macro2::TokenTree::Punct(ref p) if p.as_char() == ',') {
                pos += 1;
                continue;
            }

            if pos >= tts.len() {
                break;
            }

            // Collect arg tokens until top-level comma or EOF
            let (arg_trees, end_pos) = collect_arg_trees(&tts, pos);
            if arg_trees.is_empty() {
                break;
            }
            let arg_tokens: proc_macro2::TokenStream = arg_trees.iter().cloned().collect();
            let (name, expr_ts) = parse_arg(&arg_tokens).unwrap_or((None, arg_tokens));
            args.push((name, expr_ts));
            pos = end_pos;
        }

        Ok(Self {
            format_string,
            format_literal,
            args,
        })
    }

    /// [autogenerated by LLM] Phase 3 — Emit the final `core::format_args!()` call.
    ///
    /// Takes the parsed IR and produces a `TokenStream` that expands to:
    /// `core::format_args!("..." , wrapped_or_raw_arg1, wrapped_or_raw_arg2, ...)`
    ///
    /// ## Wrapping decision logic
    ///
    /// For each argument in `self.args`, the method looks up its `WrapKind`
    /// in the format string analysis:
    ///
    /// - **Named args**: looked up by binding name in `analysis.named`.
    /// - **Positional args without auto-nexting**: looked up by index in `analysis.positional`.
    /// - **Positional args WITH auto-nexting**: the set of format traits used across
    ///   all auto-placeholders is examined. If all auto-placeholders use the same trait,
    ///   that wrapper is used. If they differ, `TryDisplayWrapper` is used as fallback.
    ///
    /// The wrapper struct is chosen based on the `WrapKind`:
    /// - `Debug` → `TryDebugWrapper::new(...)`
    /// - `Display` / `Multi` → `TryDisplayWrapper::new(...)`
    /// - `LowerHex` → `TryLowerHexWrapper::new(...)`
    /// - `UpperHex` → `TryUpperHexWrapper::new(...)`
    /// - `Measure` / absent → emitted unwrapped
    ///
    /// Named bindings are re-emitted as `name = Wrapper::new(expr)` to preserve
    /// the named-binding syntax that `core::format_args!` expects.
    fn emit(&self) -> proc_macro2::TokenStream {
        let fmt_str = &self.format_string;
        let fmt_lit = &self.format_literal;
        let analysis = analyze_format_string(fmt_str);

        // Determine the default kind for auto-nexted arguments.
        // If all auto-placeholders agree on one kind, use it. Otherwise fall back to Display.
        let auto_default = if analysis.auto_kinds.is_empty() {
            None
        } else {
            let first = analysis.auto_kinds[0];
            if analysis.auto_kinds.iter().all(|&k| k == first) {
                Some(first)
            } else {
                Some(WrapKind::Display)
            }
        };

        let mut formatted_args = Vec::new();

        for (i, (maybe_name, expr_ts)) in self.args.iter().enumerate() {
            let kind = match maybe_name.as_ref() {
                Some(name) => analysis.named.get(name.as_str()).copied(),
                None => {
                    if auto_default.is_some() {
                        auto_default
                    } else {
                        analysis.positional.get(&i).copied()
                    }
                }
            };

            let wrapper_call = kind.map(|k| match k {
                WrapKind::Debug => {
                    quote! { ::rustyfill::try_fmt::TryDebugWrapper::new(&(#expr_ts)) }
                }
                WrapKind::Display | WrapKind::Multi => {
                    quote! { ::rustyfill::try_fmt::TryDisplayWrapper::new(&(#expr_ts)) }
                }
                WrapKind::LowerHex => {
                    quote! { ::rustyfill::try_fmt::TryLowerHexWrapper::new(&(#expr_ts)) }
                }
                WrapKind::UpperHex => {
                    quote! { ::rustyfill::try_fmt::TryUpperHexWrapper::new(&(#expr_ts)) }
                }
                WrapKind::LowerExp => {
                    quote! { ::rustyfill::try_fmt::TryLowerExpWrapper::new(&(#expr_ts)) }
                }
                WrapKind::UpperExp => {
                    quote! { ::rustyfill::try_fmt::TryUpperExpWrapper::new(&(#expr_ts)) }
                }
                WrapKind::Measure => expr_ts.clone(),
            });

            if let Some(name) = maybe_name {
                let name_ident = syn::Ident::new(name, proc_macro2::Span::call_site());
                if let Some(wrapped) = wrapper_call {
                    formatted_args.push(quote! {
                        #name_ident = #wrapped
                    });
                } else {
                    formatted_args.push(quote! {
                        #name_ident = #expr_ts
                    });
                }
            } else if let Some(wrapped) = wrapper_call {
                formatted_args.push(wrapped);
            } else {
                formatted_args.push(expr_ts.clone());
            }
        }

        if formatted_args.is_empty() {
            quote! {
                core::format_args!(#fmt_lit)
            }
        } else {
            quote! {
                core::format_args!(#fmt_lit , #(#formatted_args),*)
            }
        }
    }
}

/// [autogenerated by LLM] Collect token trees for one argument from position `start`
/// until a top-level comma or EOF.
///
/// Walks the token array left-to-right, tracking grouping depth (`{}`, `[]`, `()`).
/// A comma at depth 0 terminates the argument. The terminating comma itself is
/// consumed (skipped) so that the caller's next iteration starts after it.
///
/// Returns `(collected_trees, next_position)` where `next_position` points to the
/// first unconsumed token after the comma (or `tts.len()` if EOF was reached).
fn collect_arg_trees(
    tts: &[proc_macro2::TokenTree],
    start: usize,
) -> (Vec<proc_macro2::TokenTree>, usize) {
    let mut collected = Vec::new();
    let mut depth: i32 = 0;
    let mut pos = start;

    while pos < tts.len() {
        match &tts[pos] {
            proc_macro2::TokenTree::Group(_) => {
                depth += 1;
                collected.push(tts[pos].clone());
                pos += 1;
            }
            proc_macro2::TokenTree::Punct(p) if p.as_char() == ',' && depth == 0 => {
                // Skip the comma too
                pos += 1;
                break;
            }
            _ => {
                collected.push(tts[pos].clone());
                pos += 1;
            }
        }
    }

    (collected, pos)
}

/// [autogenerated by LLM] Detect whether an argument has a named binding (`name = expr`).
///
/// Scans the token stream for the first `=` at grouping depth 0. If found AND the
/// first token at depth 0 is an identifier, treats the argument as a named binding:
/// returns `(Some(name), expr_tokens_after_eq)`.
///
/// Otherwise returns `(None, full_token_stream)` — a positional argument whose
/// entire token stream is the expression.
///
/// ## Edge cases handled
///
/// - `Foo::BAR = x`: the first ident is `Foo`, which becomes the name. This matches
///   how `format_args!` handles named bindings (only simple identifiers are valid names).
/// - `a + b = c`: the first ident is `a`, so this would be misidentified as named.
///   However, `format_args!` itself rejects this syntax, so the downstream compiler
///   error is acceptable.
/// - `foo(bar) = baz`: the `=` is at depth 0 but the first ident at depth 0 is `foo`,
///   so this correctly identifies `foo` as the name.
fn parse_arg(
    tokens: &proc_macro2::TokenStream,
) -> syn::Result<(Option<String>, proc_macro2::TokenStream)> {
    let mut depth = 0u32;
    let mut eq_pos_found = false;
    let mut first_ident = None;

    for tt in tokens.clone().into_iter() {
        match &tt {
            proc_macro2::TokenTree::Group(_) => {
                depth += 1;
            }
            proc_macro2::TokenTree::Punct(p) if p.as_char() == '=' && depth == 0 => {
                eq_pos_found = true;
                break;
            }
            proc_macro2::TokenTree::Ident(id) if first_ident.is_none() && depth == 0 => {
                first_ident = Some(id.clone());
            }
            _ => {}
        }
    }

    if eq_pos_found {
        if let Some(ident) = first_ident {
            let name = ident.to_string();
            let expr_tokens = split_after_eq(tokens);
            return Ok((Some(name), expr_tokens));
        }
    }

    Ok((None, tokens.clone()))
}

/// [autogenerated by LLM] Extract only the tokens appearing after the first top-level `=`.
///
/// Used by `parse_arg()` to isolate the expression portion of a named binding.
/// Tokens before and including the `=` are discarded. Grouping depth is NOT tracked
/// here because the `=` we care about is always at depth 0 (guaranteed by `parse_arg`).
fn split_after_eq(tokens: &proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    let mut out = proc_macro2::TokenStream::new();
    let mut past_eq = false;

    for tt in tokens.clone() {
        match &tt {
            proc_macro2::TokenTree::Group(_) => {
                if past_eq {
                    out.extend(proc_macro2::TokenStream::from(tt));
                }
            }
            proc_macro2::TokenTree::Punct(p) if p.as_char() == '=' => {
                past_eq = true;
            }
            _ => {
                if past_eq {
                    out.extend(proc_macro2::TokenStream::from(tt));
                }
            }
        }
    }

    out
}

/* ── Format string analysis (Phase 2 — AST generation) ─────────────────────── */

/// [autogenerated by LLM] Result of analyzing a format string.
///
/// Maps each argument slot (by positional index or by name) to its `WrapKind`,
/// indicating which wrapper type should be emitted for that argument.
/// The `auto_kinds` field tracks which format traits are used by auto-nexting
/// placeholders, so emission can pick the right wrapper even without explicit indices.
///
/// This struct is the closest thing to an "AST" in this module. It is not a tree
/// but a flat lookup table that tells `emit()` which wrapper to use per argument.
struct FormatAnalysis {
    /// Maps positional argument index → which wrapper kind it needs.
    positional: BTreeMap<usize, WrapKind>,
    /// Maps named binding name → which wrapper kind it needs.
    named: BTreeMap<String, WrapKind>,
    /// The set of wrapper kinds used by auto-nexting (`{}`) placeholders.
    /// Empty if no auto-nexting placeholders exist. If multiple distinct kinds
    /// are present, emission falls back to `TryDisplayWrapper` as the safest default.
    auto_kinds: Vec<WrapKind>,
}

/// [autogenerated by LLM] Phase 2 — Analyze the format string and build the usage map.
///
/// Walks the format string character-by-character with a `Peekable<char>` iterator.
/// This is the core AST-generation function: it determines which wrapper type each
/// argument slot needs based on the trailing format character of each placeholder.
///
/// ## Algorithm
///
/// 1. Scan left-to-right. Skip non-`{` characters entirely (literal text).
/// 2. On `{`, check for escaped brace `{{` — if so, skip and continue.
/// 3. Otherwise, this is a placeholder. Call `parse_arg_spec()` to classify
///    the argument reference (positional, named, or auto).
/// 4. If `ArgKind::Auto` is detected, set `has_auto = true`.
/// 5. If a `:` follows the arg spec, consume it and call `parse_format_spec()`
///    to walk through alignment, sign, flags, width, precision, and format char.
///    Returns the trailing format character (if any). Dynamic references like
///    `{0$}` or `{w$}` are recorded as `WrapKind::Measure`.
/// 6. Determine the wrapper kind from the format char: `?` → Debug, `x` → LowerHex,
///    `X` → UpperHex, anything else (including none) → Display.
/// 7. Consume the closing `}`.
/// 8. Merge the wrapper kind into the slot's entry via `merge_kind_*()`.
///
/// ## Why character-by-character instead of regex?
///
/// Regex would struggle with nested braces in dynamic width/precision (`{0$}`)
/// and escaped braces (`{{`). A manual state machine handles these correctly
/// with minimal overhead. The format string is small (< a few KB typically),
/// so performance is irrelevant.
fn analyze_format_string(s: &str) -> FormatAnalysis {
    let mut positional = BTreeMap::new();
    let mut named = BTreeMap::new();
    let mut auto_kinds = Vec::new();
    let mut chars = s.chars().peekable();

    while let Some(c) = chars.next() {
        if c != '{' {
            continue;
        }
        if chars.peek() == Some(&'{') {
            chars.next();
            continue;
        }

        let kind = parse_arg_spec(&mut chars);

        let fmt_char = if chars.peek() == Some(&':') {
            chars.next();
            parse_format_spec(&mut chars, &mut positional, &mut named)
        } else {
            None
        };

        let _ = chars.next(); // consume closing }

        let wrap = match fmt_char {
            Some('?') => WrapKind::Debug,
            Some('x') => WrapKind::LowerHex,
            Some('X') => WrapKind::UpperHex,
            Some('e') => WrapKind::LowerExp,
            Some('E') => WrapKind::UpperExp,
            _ => WrapKind::Display,
        };

        match kind {
            ArgKind::Positional(idx) => {
                merge_kind_p(&mut positional, idx, wrap);
            }
            ArgKind::Named(name) => {
                merge_kind_n(&mut named, name, wrap);
            }
            ArgKind::Auto => {
                auto_kinds.push(wrap);
            }
        }
    }

    FormatAnalysis {
        positional,
        named,
        auto_kinds,
    }
}

/// [autogenerated by LLM] Classifies the argument reference inside a `{...}` placeholder.
///
/// Determines how the placeholder refers to its argument:
/// - `Positional(idx)` — explicit numeric index, e.g., `{0}`, `{42}`
/// - `Named(name)` — alphanumeric identifier, e.g., `{foo}`, `{my_var}`
/// - `Auto` — bare `{}`, `{:spec}`, or unrecognized syntax. These use Rust's
///   auto-nexting mechanism where the compiler assigns sequential indices.
#[derive(Debug)]
enum ArgKind {
    Positional(usize),
    Named(String),
    Auto,
}

/// [autogenerated by LLM] Parse the argument specification at the current cursor position.
///
/// Called immediately after entering a `{` (non-escaped) placeholder. Reads ahead
/// to determine what kind of argument reference follows.
///
/// ## Recognition rules (in priority order)
///
/// 1. If next char is `:` or `}` → `ArgKind::Auto` (bare placeholder or spec-only).
/// 2. If next char is an ASCII digit → consume all consecutive digits, parse as
///    `usize`, return `ArgKind::Positional(idx)`. Overflow falls back to 0.
/// 3. Otherwise → consume alphanumeric + `_` characters as a name. If non-empty,
///    return `ArgKind::Named(name)`. If empty (e.g., the first char was neither
///    digit nor alpha), return `ArgKind::Auto`.
fn parse_arg_spec<I>(chars: &mut std::iter::Peekable<I>) -> ArgKind
where
    I: Iterator<Item = char>,
{
    let Some(&c) = chars.peek() else {
        return ArgKind::Auto;
    };

    if c == ':' || c == '}' {
        return ArgKind::Auto;
    }

    if c.is_ascii_digit() {
        let mut num = String::new();
        while let Some(&ch) = chars.peek() {
            if ch.is_ascii_digit() {
                num.push(ch);
                chars.next();
            } else {
                break;
            }
        }
        let idx = num.parse::<usize>().unwrap_or(0);
        ArgKind::Positional(idx)
    } else {
        let mut name = String::new();
        while let Some(&ch) = chars.peek() {
            if ch.is_alphanumeric() || ch == '_' {
                name.push(ch);
                chars.next();
            } else {
                break;
            }
        }
        if name.is_empty() {
            ArgKind::Auto
        } else {
            ArgKind::Named(name)
        }
    }
}

/// [autogenerated by LLM] Parse the format spec that follows `:` inside a placeholder.
///
/// Consumes the format spec components in the exact order defined by Rust's
/// formatting mini-language. Each component is optional and recognized by its
/// leading character. Returns the trailing format character (if any), which the
/// caller uses to determine the wrapper kind.
///
/// ## Component order (matches `std::fmt` specification)
///
/// 1. **Alignment** (`<`, `>`, `^`, `=`): at most one character. Controls text
///    alignment within the field width.
/// 2. **Sign** (`+`, `-`, ` `): at most one character. Controls sign display for
///    numeric types.
/// 3. **Alternate flag** (`#`): enables alternate output format (e.g., `0x` prefix
///    for hex integers).
/// 4. **Zero-padding** (`0`): pads with zeros instead of spaces. Only meaningful
///    when combined with a width specifier.
/// 5. **Width**: delegated to `parse_width_or_precision()`. Can be a literal number,
///    `*` (dynamic from args), or `N$` / `name$` (dynamic from specific arg).
///    Dynamic references are recorded as `WrapKind::Measure`.
/// 6. **Precision** (`.` followed by width-like syntax): same structure as width.
///    If `.` is present, consume it and delegate again to `parse_width_or_precision()`.
/// 7. **Format char**: a single trailing character specifying output type
///    (`?`, `d`, `x`, `X`, `o`, `b`, `e`, `E`, etc.). Consumed if present and not `}`.
///
/// Note: this parser does NOT validate the spec (that's the compiler's job via
/// `core::format_args!`). It only needs to identify dynamic width/precision refs
/// and the trailing format character.
fn parse_format_spec<I>(
    chars: &mut std::iter::Peekable<I>,
    positional: &mut BTreeMap<usize, WrapKind>,
    named: &mut BTreeMap<String, WrapKind>,
) -> Option<char>
where
    I: Iterator<Item = char>,
{
    // Flags & alignment — these can appear in any order in Rust's format spec.
    // We loop until none of the recognized flag/alignment characters remain.
    // This handles permutations like `0>`, `#010`, `+^`, etc.
    loop {
        match chars.peek().copied() {
            Some('<' | '>' | '^' | '=') => {
                chars.next();
            }
            Some('+' | '-' | ' ') => {
                chars.next();
            }
            Some('#') => {
                chars.next();
            }
            Some('0') => {
                chars.next();
            }
            _ => break,
        };
    }

    // Width — may be a literal number, '*', or a dynamic reference (N$ or name$)
    parse_width_or_precision(chars, positional, named);

    // Precision
    if let Some('.') = chars.peek() {
        chars.next();
        parse_width_or_precision(chars, positional, named);
    }

    // At this point in the spec, the next token could be:
    //   - A named dynamic reference like `w$` (identifier + '$')
    //   - A trailing format character like `x` or `?` (single char)
    // Both start with an alphabetic character. We disambiguate by looking ahead
    // to see if the identifier is followed by '$'.
    if matches!(chars.peek(), Some(c) if c.is_alphabetic() || *c == '_') {
        // Consume the full identifier into a buffer.
        let mut ident = String::new();
        while let Some(&ch) = chars.peek() {
            if ch.is_alphanumeric() || ch == '_' {
                ident.push(ch);
                chars.next();
            } else {
                break;
            }
        }
        match chars.peek().copied() {
            Some('$') => {
                // Named dynamic reference: consume '$' and record it.
                chars.next();
                merge_kind_n(named, ident, WrapKind::Measure);
                // Continue scanning for a trailing format character after name$.
            }
            _ => {
                // No '$' — this is the trailing format character itself.
                // Per Rust's format spec grammar, the format char is exactly
                // one character (? x X o b p e E L), so take the first char.
                return ident.chars().next();
            }
        }
    }

    // Additional format character — returned to the caller so it can determine
    // the wrapper kind (Debug, Display, LowerHex, UpperHex).
    if let Some(&c) = chars.peek() {
        if c != '}' {
            chars.next();
            return Some(c);
        }
    }
    None
}

/// [autogenerated by LLM] Parse a width or precision value within a format spec.
///
/// This function is called twice per format spec: once for width, once for precision
/// (if `.` was present). It handles two syntaxes:
///
/// ## Syntax variants
///
/// ### Star width: `*`
/// A lone `*` means "take the width from the next positional argument." We consume
/// the `*` and return without recording any slot usage, because the star-width
/// mechanism is handled internally by `core::format_args!` using its own positional
/// counting — our wrapper doesn't need to track those slots separately.
///
/// ### Literal number: `5`, `10`, `256`
/// A plain digit sequence with no trailing `$` is a hardcoded width/precision.
/// We consume the digits but do NOT record any slot usage — no argument is referenced.
///
/// ### Dynamic positional ref: `0$`, `1$`, `42$`
/// A digit sequence followed by `$` references a specific positional argument by index.
/// We parse the index and record it as `WrapKind::Measure` in the positional map,
/// indicating that this argument supplies a numeric value rather than displayed content.
///
/// Note: named dynamic references (`w$`) are handled by `parse_format_spec` directly,
/// not by this function, to avoid ambiguity with trailing format characters like `x`.
fn parse_width_or_precision<I>(
    chars: &mut std::iter::Peekable<I>,
    positional: &mut BTreeMap<usize, WrapKind>,
    _named: &mut BTreeMap<String, WrapKind>,
) where
    I: Iterator<Item = char>,
{
    let Some(&c) = chars.peek() else {
        return;
    };

    if c == '*' {
        chars.next();
        return;
    }

    if c.is_ascii_digit() {
        let mut num = String::new();
        while let Some(&ch) = chars.peek() {
            if ch.is_ascii_digit() {
                num.push(ch);
                chars.next();
            } else {
                break;
            }
        }
        if let Some('$') = chars.peek() {
            chars.next();
            let idx = num.parse::<usize>().unwrap_or(0);
            merge_kind_p(positional, idx, WrapKind::Measure);
        }
        // If no '$', the digits are a literal width — already consumed, done.
    }
    // Alphabetic characters are NOT handled here — they may be either named
    // dynamic refs (handled by parse_format_spec) or trailing format chars.
}

/// [autogenerated by LLM] Merge a new wrapper kind into the positional map.
///
/// If the slot has no existing entry, inserts the new kind directly.
/// If the slot already has an entry, delegates to `WrapKind::merge()`.
/// Uses remove-then-insert to mutate the value in place.
fn merge_kind_p(map: &mut BTreeMap<usize, WrapKind>, key: usize, new: WrapKind) {
    let merged = map.remove(&key).map_or(new, |existing| existing.merge(new));
    map.insert(key, merged);
}

/// [autogenerated by LLM] Merge a new wrapper kind into the named map.
///
/// Identical logic to `merge_kind_p()` but operates on the `BTreeMap<String, WrapKind>`
/// for named bindings.
fn merge_kind_n(map: &mut BTreeMap<String, WrapKind>, key: String, new: WrapKind) {
    let merged = map.remove(&key).map_or(new, |existing| existing.merge(new));
    map.insert(key, merged);
}
