//! System-level data structure bindings for rustyfill.
//!
//! This crate mirrors data structures from the Rust standard library (core, alloc, std)
//! with identical field layout and alignment. All types are intentionally made public.
//!
//! Here be dragons! Note that drop implementations may or may not exist.
//!
//! Generated at build time by `build.rs` using `rustyfill-sys-bindings`.
//!
//! # Module structure
//!
//! The module hierarchy mirrors the source library paths. For example, a type from
//! `std::sys::pal::unix::sync::mutex` in the standard library is accessible as
//! `rustyfill_sys::std::sys::pal::unix::sync::mutex::Mutex`.
//!
//! Alias paths (e.g., `std::sys::pal::sync::Mutex`) re-export from their canonical
//! location to avoid duplicate definitions.
//!
//! # Builtin crates
//!
//! The real `core`, `alloc`, and `std` crates are reserved under mangled names
//! (`__rustyfill_builtin_core`, `__rustyfill_builtin_alloc`, `__rustyfill_builtin_std`)
//! so that generated bindings can reference them via absolute paths without colliding
//! with the synthetic `core`/`alloc`/`std` modules that mirror the library's internal
//! structure.

#![no_std]

/// Reserved extern name for the real `core` crate.
/// Known core types that do not need polyfills are imported through this path.
pub extern crate core as __rustyfill_builtin_core;

/// Reserved extern name for the real `alloc` crate.
/// Known alloc types that do not need polyfills are imported through this path.
pub extern crate alloc as __rustyfill_builtin_alloc;

/// Reserved extern name for the real `std` crate.
/// Known std types that do not need polyfills are imported through this path.
#[cfg(feature = "std")]
pub extern crate std as __rustyfill_builtin_std;

// Include the hierarchical module tree generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/bindings_generated.rs"));
