//! Fallible construction and arming for [`lang_std::sync::Mutex`].
//!
//! The platform backends of std's `Mutex` differ in when they allocate:
//!
//! - **futex** (Linux, Android, FreeBSD, OpenBSD, WASM atomics, Hermit, ...) —
//!   the sys mutex is a single atomic word. Construction never touches the heap.
//! - **pthread** (macOS, iOS, most other Unix targets) — the sys mutex wraps an
//!   `OnceBox<pal::Mutex>` that lazily allocates and initialises the backing
//!   `pthread_mutex_t` on the *first* lock, so construction looks infallible
//!   but the allocation cost is deferred and can still abort under memory
//!   pressure.
//!
//! [`TryMutex`] gives two families of fallible operations:
//!
//! **Construction.** Every `try_new*` constructor performs all the backend
//! allocation up front and returns an *armed* mutex — one whose `.lock()` is
//! guaranteed not to allocate (and therefore not to abort) again. They follow
//! the same conventions as [`TryBox`](crate::alloc::boxed::TryBox):
//!
//! - [`try_new`](TryMutex::try_new) / [`try_new_give_back`](TryMutex::try_new_give_back)
//!   build a fully-initialised `Mutex<T>` holding a value.
//! - [`try_new_uninit`](TryMutex::try_new_uninit) and
//!   [`try_new_zeroed`](TryMutex::try_new_zeroed) return a low-level
//!   `Mutex<MaybeUninit<T>>` whose data slot is left uninitialised or
//!   zero-filled; the caller fills it and calls
//!   [`assume_init`](TryMutex::assume_init) to obtain a typed `Mutex<T>`.
//!
//! **Arming.** A mutex created with plain [`Mutex::new`] on a pthread target is
//! *not* armed: its backend will still perform the deferred allocation on first
//! lock, which can abort under OOM. [`try_arm`](TryMutex::try_arm) performs that
//! allocation eagerly in place, converting a lazy mutex into an armed one so no
//! later call can fail. On futex targets (and for already-armed mutexes) it is
//! a no-op that always succeeds.
//!
//! All fallible entry points return [`AllocError`] on failure. See the safety
//! notes inside each backend branch for the invariants that make the
//! raw-pointer surgery sound.

cfg_select! {
    any(
        target_os = "linux",
        target_os = "android",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "motor",
        target_os = "dragonfly",
        target_os = "hermit",
        all(target_family = "wasm", target_feature = "atomics"),
    ) => {
        mod futex;
        use futex::fresh_inner_mutex;
    }
    _ => {
        mod pthread;
        use pthread::fresh_inner_mutex;
    }
}

use crate::alloc::AllocError;
use lang_core::fmt;
use lang_core::mem::{self, MaybeUninit};
use lang_std::sync::Mutex;

/// Layout mirror of std's public `sync::Mutex<T>` (the poisoned variant),
/// generated by `rustyfill-sys` from the standard library source. Its fields
/// are public here, which lets us construct and inspect the exact byte layout
/// of the real type without going through unstable APIs.
pub(crate) type SysMutexMirror<T> = rustyfill_sys::std::sync::poison::mutex::Mutex<T>;
/// Mirror of the cfg-selected sys mutex (`std::sys::sync::mutex::Mutex`). On
/// futex platforms this forwards to the single-atomic-word implementation; on
/// pthread platforms to the `OnceBox<pal::Mutex>` wrapper. Constructed
/// field-by-field below rather than via a `Default` impl, so we control exactly
/// what bytes land in each slot.
pub(crate) type SysInnerMutex = rustyfill_sys::std::sys::sync::mutex::Mutex;
/// Mirror of the poison flag carried by every public `Mutex`. Fresh state is
/// "not failed", matching what `Mutex::new` produces.
pub(crate) type PoisonFlag = rustyfill_sys::std::sync::poison::Flag;

/// Construct an instance of the generated mirror's atomic primitive — a
/// transparent wrapper around a public `UnsafeCell<T>`, standing in for std's
/// generic atomic (which won't compile downstream). Delegates to the stub's own
/// `new`, which lays down exactly the bytes std's `Atomic::new(v)` produces.
pub(crate) fn mirror_atomic<T>(value: T) -> rustyfill_sys::std::sync::atomic::Atomic<T> {
    rustyfill_sys::std::sync::atomic::Atomic::new(value)
}

/// Fallible construction and arming for [`Mutex`].
///
/// Implemented for [`Mutex<T>`]. Mirrors the [`TryBox`](crate::alloc::boxed::TryBox)
/// pattern: the allocating entry points are fallible; all other mutex behaviour
/// (locking, unlocking, poisoning) delegates to the standard library.
///
/// Every `try_new*` constructor returns an **armed** mutex — one whose `.lock()`
/// will not allocate again. A mutex made with plain [`Mutex::new`] can be
/// upgraded in place via [`try_arm`](Self::try_arm).
///
/// # Examples
///
/// ```rust
/// use rustyfill::prelude::*;
/// use std::sync::Mutex;
///
/// // One-shot: armed mutex holding a value.
/// let m: Mutex<i32> = Mutex::try_new(42).expect("alloc");
/// assert_eq!(*m.lock().unwrap(), 42);
///
/// // Low-level two-phase: allocate an armed shell, fill it, activate it.
/// let mut uninit: Mutex<core::mem::MaybeUninit<i32>> =
///     Mutex::<i32>::try_new_uninit().expect("alloc");
/// *uninit.get_mut().unwrap() = core::mem::MaybeUninit::new(7); // write the slot
/// let m = unsafe { Mutex::assume_init(uninit) };
/// assert_eq!(*m.lock().unwrap(), 7);
///
/// // Repair a lazily-constructed mutex so its first lock cannot abort.
/// let lazy = Mutex::new(0u8);
/// Mutex::try_arm(&lazy).expect("arm");
/// *lazy.lock().unwrap() += 1;
/// ```
pub trait TryMutex<T>: Sized {
    /// Fallibly construct a fully-initialised, unlocked **armed** `Mutex<T>`
    /// holding `value`.
    ///
    /// Performs every allocation the platform backend needs up front, so the
    /// returned mutex's `.lock()` will never allocate again. Returns
    /// [`AllocError`] if the backend allocation fails.
    fn try_new(value: T) -> Result<Mutex<T>, AllocError>;

    /// Like [`try_new`](Self::try_new) but returns ownership of `value` back on
    /// failure, so no data is lost to an OOM.
    fn try_new_give_back(value: T) -> Result<Mutex<T>, (T, AllocError)>;

    /// Fallibly construct an **armed** `Mutex<MaybeUninit<T>>` whose data slot
    /// is left uninitialised.
    ///
    /// This is the low-level primitive: all backend allocation happens here, so
    /// the returned mutex is armed. Fill the slot through
    /// [`Mutex::get_mut`](lang_std::sync::Mutex::get_mut) and convert with
    /// [`assume_init`](Self::assume_init).
    fn try_new_uninit() -> Result<Mutex<MaybeUninit<T>>, AllocError>;

    /// Fallibly construct an **armed** `Mutex<MaybeUninit<T>>` whose data slot
    /// is zero-filled.
    ///
    /// The slot holds all-zero bytes rather than being left uninitialised. This
    /// is only meaningful for types where an all-zero bit pattern is a valid
    /// value (ints, arrays, pointers, ZSTs); the caller is responsible for that
    /// precondition before calling [`assume_init`](Self::assume_init).
    fn try_new_zeroed() -> Result<Mutex<MaybeUninit<T>>, AllocError>;

    /// Convert a `Mutex<MaybeUninit<T>>` whose data slot has been written into
    /// a real `Mutex<T>`.
    ///
    /// # Safety
    ///
    /// The caller must guarantee that the data slot has been fully initialised
    /// (e.g. via `MaybeUninit::write` or `MaybeUninit::zeroed`) before calling
    /// this. Reading an unwritten slot is undefined behaviour. Because the input
    /// type is `Mutex<MaybeUninit<T>>`, the compiler enforces that you obtained
    /// it from [`try_new_uninit`](Self::try_new_uninit) or
    /// [`try_new_zeroed`](Self::try_new_zeroed) — there is no other source.
    unsafe fn assume_init(this: Mutex<MaybeUninit<T>>) -> Mutex<T>;

    /// Arm an existing mutex, performing any deferred backend allocation in
    /// place so that no later call can fail.
    ///
    /// A mutex created with plain [`Mutex::new`] on a pthread target is *lazy*:
    /// its backing `pthread_mutex_t` is not allocated until the first lock, at
    /// which point an OOM would abort the process. Calling this method forces
    /// that allocation now and reports failure via [`AllocError`] instead. After
    /// a successful return, the mutex is armed and `.lock()` is guaranteed
    /// infallible.
    ///
    /// This is idempotent: arming an already-armed mutex (one built by any
    /// `try_new*` constructor, or already locked once) is a no-op that succeeds.
    /// On futex targets construction never allocates, so this always succeeds.
    ///
    /// Takes a shared reference because the only mutation is to the backend's
    /// interior-mutable atomic pointer cell — the same reason std's
    /// `OnceBox::get_or_init(&self)` needs no exclusive access.
    fn try_arm(&self) -> Result<(), AllocError>;

    // ── Aliases with `fallible_` prefix ─────────────────────────────────────

    /// Alias for [`Self::try_new_uninit`].
    fn fallible_new_uninit() -> Result<Mutex<MaybeUninit<T>>, AllocError> {
        Self::try_new_uninit()
    }

    /// Alias for [`Self::try_new_zeroed`].
    fn fallible_new_zeroed() -> Result<Mutex<MaybeUninit<T>>, AllocError> {
        Self::try_new_zeroed()
    }
}

// ── Shared helpers ────────────────────────────────────────────────────────────

/// Compile-time proof that two types share size and alignment — the precondition
/// for treating one as a byte-for-byte re-tagging of the other. Mirrors the
/// `const _: () = assert!(…)` idiom used elsewhere in the crate (see
/// [`crate::alloc`]). If a mirror ever drifts from its real counterpart this
/// fails at compile time rather than silently corrupting values at runtime.
const fn assert_layout<A, B>() {
    const {
        assert!(
            mem::size_of::<A>() == mem::size_of::<B>(),
            "assert_layout: A and B differ in size"
        );
        assert!(
            mem::align_of::<A>() == mem::align_of::<B>(),
            "assert_layout: A and B differ in alignment"
        );
    }
}

/// Move a whole value from one layout-identical type to another.
///
/// Copies the bytes out of `src` into a new destination-typed value, then drops
/// `src`'s ownership without running its destructor — i.e. a true move, not a
/// clone followed by a drop. This is sound only when `From` and `To` share size
/// and alignment (checked by the caller via [`assert_layout`]) and the bytes are
/// a valid `To`.
unsafe fn move_retag<From, To>(src: From) -> To {
    // SAFETY: caller guarantees `From` and `To` are size/alignment-identical and
    // that `src`'s bytes form a valid `To`. `transmute_copy` reads those bytes
    // into a fresh `To`; forgetting `src` transfers ownership so its destructor
    // does not run a second time on the now-reinterpreted memory.
    let dest = unsafe { mem::transmute_copy(&src) };
    mem::forget(src);
    dest
}

/// Build a public `Mutex<T>` shell holding `data` and carrying a freshly-created
/// (unlocked, unallocated) sys mutex plus a fresh poison flag. Used by both
/// backend branches as the starting point.
///
/// SAFETY contract for callers: the caller must ensure `data` is a valid value
/// of the declared payload type. When the payload is `MaybeUninit<U>`, pass
/// `MaybeUninit::uninit()`; the slot stays logically uninitialised until the
/// caller writes through it. Locking before the payload is ready is UB. The sys
/// mutex itself is in the exact state `sys::Mutex::new()` produces, so all
/// backend invariants hold.
pub(crate) fn shell<T>(data: T) -> Mutex<T> {
    // Construct the layout mirror field-by-field. The mirrors are pure data
    // structs (no constructors), so we replicate exactly what std's
    // `sys::Mutex::new()` + `Flag::new()` write into each slot:
    //
    //   - `inner`:  the cfg-selected sys mutex, freshly unlocked / unallocated
    //               (futex: the atomic word set to UNLOCKED; pthread: a null
    //                 OnceBox pointer). No heap involved on either path.
    //   - `poison`: a fresh `Flag { failed: false }`, matching `Flag::new()`.
    //   - `data`:   the supplied payload, held in an `UnsafeCell`.
    //
    // Because every field is written with the exact bytes std's own
    // constructors produce, the resulting value is indistinguishable — at the
    // byte level — from one built by `Mutex::new(data)`.
    let mirror = SysMutexMirror::<T> {
        inner: fresh_inner_mutex(),
        poison: PoisonFlag {
            #[cfg(panic = "unwind")]
            failed: mirror_atomic(false),
        },
        data: lang_core::cell::UnsafeCell::new(data),
    };
    // Prove the mirror and the real `Mutex<T>` agree in size/alignment before
    // retagging the whole value.
    assert_layout::<SysMutexMirror<T>, Mutex<T>>();
    unsafe { move_retag(mirror) }
}

/// Shared `assume_init` body: reinterpret a `Mutex<MaybeUninit<T>>` whose data
/// slot has been written as a `Mutex<T>`.
///
/// # Safety
///
/// Same contract as [`TryMutex::assume_init`]: the data slot must be fully
/// initialised. `MaybeUninit<T>` and `T` have identical size and alignment, so
/// the retag is a pure tag change over already-valid bytes.
pub(crate) unsafe fn assume_init_impl<T>(this: Mutex<MaybeUninit<T>>) -> Mutex<T> {
    // Prove the two payloads are size/alignment-identical before retagging.
    assert_layout::<Mutex<MaybeUninit<T>>, Mutex<T>>();
    unsafe { move_retag(this) }
}

impl<T: ?Sized + crate::try_fmt::TryDebug> crate::try_fmt::TryDebug for Mutex<T> {
    fn try_fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // std's Debug for Mutex is allocation-free (verified by OOM tests)
        // and already shows "<locked>" when contention prevents inspection.
        fmt::Debug::fmt(self, f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Layout parity: the transmute between the mirror and the real public
    //    Mutex type is only sound if their layouts match exactly. Assert size
    //    and alignment for both sized and unsized payloads.

    #[test]
    fn layout_parity_with_mirror() {
        use lang_core::mem::{align_of, size_of};

        macro_rules! check {
            ($t:ty) => {{
                assert_eq!(
                    size_of::<Mutex<$t>>(),
                    size_of::<SysMutexMirror<$t>>(),
                    stringify!($t)
                );
                assert_eq!(
                    align_of::<Mutex<$t>>(),
                    align_of::<SysMutexMirror<$t>>(),
                    stringify!($t)
                );
            }};
        }
        check!(i32);
        check!(u64);
        check!([u8; 16]);
        check!(());
    }

    #[test]
    fn try_new_one_shot() {
        let m: Mutex<i32> = Mutex::try_new(42).unwrap();
        assert_eq!(*m.lock().unwrap(), 42);
    }

    #[test]
    fn try_new_uninit_then_assume_init() {
        let mut uninit: Mutex<MaybeUninit<i32>> = Mutex::<i32>::try_new_uninit().unwrap();
        uninit.get_mut().unwrap().write(7);
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), 7);
    }

    #[test]
    fn try_new_uninit_zst() {
        let mut uninit: Mutex<MaybeUninit<()>> = Mutex::<()>::try_new_uninit().unwrap();
        uninit.get_mut().unwrap().write(());
        let m = unsafe { Mutex::assume_init(uninit) };
        drop(m.lock().unwrap());
    }

    #[test]
    fn try_new_zeroed_gives_zero_payload() {
        // Zero-filled slot: an int payload reads back as 0.
        let uninit: Mutex<MaybeUninit<i32>> = Mutex::<i32>::try_new_zeroed().unwrap();
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), 0);
    }

    #[test]
    fn try_new_zeroed_array_is_all_zeros() {
        let uninit: Mutex<MaybeUninit<[u8; 4]>> = Mutex::<[u8; 4]>::try_new_zeroed().unwrap();
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), [0u8; 4]);
    }

    #[test]
    fn fallible_alias_matches_try_new_uninit() {
        let mut uninit: Mutex<MaybeUninit<u64>> = Mutex::<u64>::fallible_new_uninit().unwrap();
        uninit.get_mut().unwrap().write(1);
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), 1);
    }

    #[test]
    fn fallible_alias_matches_try_new_zeroed() {
        let uninit: Mutex<MaybeUninit<i32>> = Mutex::<i32>::fallible_new_zeroed().unwrap();
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), 0);
    }

    #[test]
    fn try_arm_on_lazy_mutex_succeeds_and_locks() {
        // A plain Mutex::new is lazy on pthread targets; arming it must succeed
        // and leave it fully lockable. On futex targets it is a trivial no-op.
        // Note: arming takes &self — the mutation is confined to the backend's
        // interior-mutable atomic pointer cell.
        let lazy = Mutex::new(5u32);
        Mutex::try_arm(&lazy).expect("arm");
        *lazy.lock().unwrap() += 1;
        assert_eq!(*lazy.lock().unwrap(), 6);
    }

    #[test]
    fn try_arm_is_idempotent() {
        // Arming twice (and arming an already-armed mutex) must keep succeeding.
        let m = Mutex::try_new(0u8).unwrap();
        Mutex::try_arm(&m).expect("first arm");
        Mutex::try_arm(&m).expect("second arm");
        *m.lock().unwrap() += 1;
        assert_eq!(*m.lock().unwrap(), 1);
    }

    #[test]
    fn initialized_mutex_survives_thread_contention() {
        use lang_std::sync::Arc;
        use lang_std::thread;
        use lang_std::vec::Vec;

        let m = Arc::new(Mutex::try_new(0u64).unwrap());
        let mut handles = Vec::new();
        for i in 0..8 {
            let m = Arc::clone(&m);
            handles.push(thread::spawn(move || {
                for _ in 0..1000 {
                    *m.lock().unwrap() += i as u64;
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        // Each of the 8 threads adds its index 1000 times.
        let expected: u64 = (0..8).map(|i| i * 1000).sum();
        assert_eq!(*m.lock().unwrap(), expected);
    }

    // ── OOM behaviour ────────────────────────────────────────────────────────

    #[cfg_attr(
        not(any(
            target_os = "linux",
            target_os = "android",
            target_os = "freebsd",
            target_os = "openbsd",
            target_os = "motor",
            target_os = "dragonfly",
            target_os = "hermit",
            all(target_family = "wasm", target_feature = "atomics"),
        )),
        ignore
    )]
    #[test]
    fn futex_branch_never_allocates() {
        use rustyfill_test_allocator::{FailPolicy, with_policy};

        // Force the very next heap allocation to fail. The futex branch must
        // not allocate at all, so it still succeeds.
        let r: Result<Mutex<MaybeUninit<i32>>, AllocError> = with_policy(
            FailPolicy::fail_next_alloc(),
            <Mutex<i32> as TryMutex<i32>>::try_new_uninit,
        );
        assert!(r.is_ok());

        // And the mutex remains fully functional afterwards.
        let mut uninit = r.unwrap();
        uninit.get_mut().unwrap().write(7);
        let m = unsafe { Mutex::assume_init(uninit) };
        assert_eq!(*m.lock().unwrap(), 7);
    }

    #[cfg_attr(
        any(
            target_os = "linux",
            target_os = "android",
            target_os = "freebsd",
            target_os = "openbsd",
            target_os = "motor",
            target_os = "dragonfly",
            target_os = "hermit",
            all(target_family = "wasm", target_feature = "atomics"),
        ),
        ignore
    )]
    #[test]
    fn pthread_branch_reports_oom_and_gives_back_value() {
        use rustyfill_test_allocator::{FailPolicy, with_policy};

        // Force the very next heap allocation to fail. The pthread branch
        // reports the error via try_new_give_back, handing the original value
        // back to the caller.
        let r: Result<Mutex<i32>, (i32, AllocError)> =
            with_policy(FailPolicy::fail_next_alloc(), || {
                Mutex::<i32>::try_new_give_back(42)
            });
        let (value_back, _err) = r.unwrap_err();
        assert_eq!(value_back, 42);
    }
}
