//! Pthread backend for `TryMutex` (macOS, iOS, most other Unix targets).
//!
//! The sys mutex wraps an `OnceBox<pal::Mutex>` that lazily allocates and
//! initialises the backing `pthread_mutex_t` on the first lock. This backend
//! hoists that allocation into the `try_new*` constructors (which therefore
//! return armed mutexes) and exposes it via `try_arm` for repairing mutexes
//! built with plain `Mutex::new`.

use super::{assume_init_impl, assert_layout, mirror_atomic, shell, SysInnerMutex, TryMutex};
use crate::alloc::AllocError;
use lang_core::mem::{self, MaybeUninit};
use lang_core::pin::Pin;
use lang_core::ptr;
use lang_std::sync::Mutex;

/// Mirror of std's private `sys::sync::once_box::OnceBox<T>`, generated by
/// `rustyfill-sys` directly from the standard library source. Used to locate
/// and publish the pthread backend's lazily-allocated `pal::Mutex` pointer.
type SysOnceBox<T> = rustyfill_sys::std::sys::sync::once_box::OnceBox<T>;
/// Mirror of std's private `sys::pal::unix::sync::mutex::Mutex`, likewise
/// generated from the standard library source. Our [`PalMutex`] below is
/// layout-identical to this, so a pointer to one may be read as the other.
type SysPalMutex = rustyfill_sys::std::sys::pal::unix::sync::mutex::Mutex;

/// Rust-side owner of the pthread backend's raw `pthread_mutex_t`.
///
/// A transparent wrapper around the generated [`SysPalMutex`] mirror (itself a
/// faithful copy of std's private `sys::pal::unix::sync::mutex::Mutex`). Because
/// `#[repr(transparent)]` collapses us onto our single `SysPalMutex` field, we are
/// byte-for-byte identical to the mirror — so a heap-allocated `PalMutex` can be
/// published into the `OnceBox` slot and later read back through the mirror
/// without any translation. Wrapping the mirror (rather than redeclaring the raw
/// `pthread_mutex_t`) keeps the layout contract anchored in the generated type.
///
/// The lifetime methods take [`Pin`] to encode the invariant that a live pthread
/// mutex must not be moved. Moving an already-initialised `pthread_mutex_t` is
/// undefined behaviour; std enforces this with `impl !Unpin`, but that requires
/// nightly. We instead carry the pinning discipline explicitly: we always hold the
/// value behind a `Pin<Box<_>>` from allocation onward and never move it, which is
/// what makes calling [`Self::init`] / [`Self::destroy`] sound.
#[repr(transparent)]
struct PalMutex {
    inner: SysPalMutex,
}

unsafe impl Send for PalMutex {}
unsafe impl Sync for PalMutex {}

impl PalMutex {
    /// Construct the wrapper holding a statically-initialised placeholder.
    ///
    /// `PTHREAD_MUTEX_INITIALIZER` is valid at every address, so this is safe to
    /// build anywhere before [`Self::init`] upgrades it to a real mutex.
    const fn new() -> Self {
        PalMutex {
            inner: SysPalMutex {
                inner: lang_core::cell::UnsafeCell::new(libc::PTHREAD_MUTEX_INITIALIZER),
            },
        }
    }

    /// Address of the underlying `pthread_mutex_t`.
    #[inline]
    fn raw(&self) -> *mut libc::pthread_mutex_t {
        self.inner.inner.get()
    }

    /// Initialise the `pthread_mutex_t` in place with `PTHREAD_MUTEX_NORMAL`.
    ///
    /// Mirrors std's `pal::Mutex::init`: creating the mutex with
    /// `PTHREAD_MUTEX_NORMAL` makes same-thread re-locking deadlock (detectable)
    /// rather than exhibit the UB of default-type mutexes (see
    /// rust-lang/rust#33770). Requires `Pin<&mut Self>` because moving the
    /// struct after this call would relocate a live mutex.
    ///
    /// # Safety
    ///
    /// May only be called once per instance, and only while the instance is
    /// still at the address it was created at (guaranteed by `Pin`).
    pub(super) unsafe fn init(self: Pin<&mut Self>) {
        // SAFETY: `self` is a valid, uniquely-located `PalMutex`; the attribute
        // object is local and freshly allocated on the stack.
        unsafe {
            let mut attr = MaybeUninit::<libc::pthread_mutexattr_t>::uninit();
            let rc = libc::pthread_mutexattr_init(attr.as_mut_ptr());
            debug_assert_eq!(rc, 0);
            let rc = libc::pthread_mutexattr_settype(attr.as_mut_ptr(), libc::PTHREAD_MUTEX_NORMAL);
            debug_assert_eq!(rc, 0);
            let rc = libc::pthread_mutex_init(self.raw(), attr.as_ptr());
            debug_assert_eq!(rc, 0);
            let rc = libc::pthread_mutexattr_destroy(attr.as_mut_ptr());
            debug_assert_eq!(rc, 0);
        }
    }

    /// Destroy the `pthread_mutex_t` in place.
    ///
    /// Mirrors std's `Drop for pal::Mutex`. Requires `Pin<&Self>` for the same
    /// reason as [`Self::init`]: the mutex must still be where it was created.
    ///
    /// # Safety
    ///
    /// The mutex must be unlocked and must have been created at this address.
    pub(super) unsafe fn destroy(self: Pin<&Self>) {
        // SAFETY: `self` is an unlocked `PalMutex` at its original address.
        let rc = unsafe { libc::pthread_mutex_destroy(self.raw()) };
        if cfg!(any(target_os = "aix", target_os = "dragonfly")) {
            // On AIX and DragonFly, destroying a mutex that was only ever built
            // with PTHREAD_MUTEX_INITIALIZER (never locked or re-init'd) returns
            // EINVAL. See std's Drop impl for the same caveat.
            debug_assert!(rc == 0 || rc == libc::EINVAL);
        } else {
            debug_assert_eq!(rc, 0);
        }
    }
}

/// Build the pthread sys-mutex mirror in its freshly-constructed state — an
/// empty `OnceBox` (null pointer). The backing `pal::Mutex` is allocated
/// lazily: eagerly in the `try_new*` constructors / `try_arm`, or natively on
/// first lock if none of those run.
pub(super) fn fresh_inner_mutex() -> SysInnerMutex {
    SysInnerMutex {
        pal: SysOnceBox {
            ptr: mirror_atomic(ptr::null_mut()),
        },
    }
}

/// Allocate, initialise, and publish a `pal::Mutex` into the `OnceBox` pointed
/// to by `slot`.
///
/// The generated mirror's atomic primitive (`rustyfill_sys::...::atomic::Atomic<T>`)
/// is a `#[repr(transparent)]` wrapper around `UnsafeCell<T>` and exposes no
/// atomic operations — it stands in for std's generic atomic purely so the
/// layout mirrors compile downstream. Here we view its single word as a real
/// [`lang_core::sync::atomic::AtomicPtr`] (identical size and alignment, both
/// just a machine-width pointer) so we can perform the load/CAS that std's own
/// `OnceBox::initialize` performs.
///
/// This mirrors std's `OnceBox::get_or_init`: a cheap acquire-load fast path
/// returns immediately if the slot is already populated, and only the slow path
/// allocates. Returns `Ok(())` when the slot ends up populated (either by this
/// call or already by a prior arming / first-lock), and `Err(AllocError)` only
/// when the allocation fails and the slot is left untouched. Idempotent.
///
/// # Safety
///
/// `slot` must reference the `OnceBox` pointer cell of a valid `Mutex<_>`, and
/// the caller must guarantee no other alias to that cell exists except through
/// this atomic. Publishing uses the same Release/Acquire CAS as std's
/// `OnceBox::initialize`.
unsafe fn arm_once_box(slot: &lang_core::sync::atomic::AtomicPtr<PalMutex>) -> Result<(), AllocError> {
    use crate::alloc::boxed::TryBox;
    use lang_alloc::boxed::Box;
    use lang_core::sync::atomic::Ordering;

    // Fast path: already armed? Nothing to do. Mirrors `get_or_init`'s leading
    // acquire-load.
    if !slot.load(Ordering::Acquire).is_null() {
        return Ok(());
    }

    // Slow path: fallibly allocate the pal mutex behind a `Pin<Box>`. Pinning
    // from the moment of allocation guarantees the `pthread_mutex_t` is never
    // moved after [`PalMutex::init`], which is what makes initialising it safe.
    // On allocation failure the slot stays null (so the native lazy path still
    // works on first lock) and the error propagates.
    let mut pinned: Pin<Box<PalMutex>> = <Box<PalMutex> as TryBox<_>>::try_pin(PalMutex::new())?;

    // SAFETY: `pinned` is a `Pin<Box<PalMutex>>`, so the value is guaranteed to
    // stay at this heap address. `as_mut()` yields a `Pin<&mut PalMutex>` for a
    // freshly allocated, not-yet-initialised instance — exactly the precondition
    // `PalMutex::init` requires.
    unsafe { pinned.as_mut().init() };

    // Unwrap the `Pin` back into the plain `Box`, then hand the box to the global
    // allocator's ownership and publish the pointer. Matches std's `initialize`:
    // `Box::into_raw` before the CAS, and on a lost race reclaim + destroy our
    // box in favour of the winner's.
    //
    // SAFETY: `into_inner_unchecked` requires that the value will not be moved
    // out of its current address after this point. We immediately turn the box
    // into a raw pointer and only ever touch the contained `PalMutex` through
    // that stable heap address (via `Pin::new_unchecked` on reclamation), so the
    // pinning invariant holds for the remainder of its life.
    let boxed = unsafe { Pin::into_inner_unchecked(pinned) };
    let new_ptr = Box::into_raw(boxed).cast::<PalMutex>();
    match slot.compare_exchange(ptr::null_mut(), new_ptr, Ordering::Release, Ordering::Acquire) {
        Ok(_) => Ok(()),
        Err(winner) => {
            // Lost the race to another thread. Reclaim our freshly-initialised
            // mutex, destroy the underlying pthread object, and free the box.
            let reclaimed = unsafe { Box::from_raw(new_ptr) };
            // SAFETY: `reclaimed` was just reconstituted from the very pointer we
            // published, so the `PalMutex` is at its original heap address and is
            // unlocked. `Pin::new_unchecked` is therefore sound, and destroying
            // the live pthread mutex in place is required before freeing.
            unsafe { Pin::new_unchecked(&*reclaimed).destroy() };
            drop(reclaimed);
            debug_assert!(!winner.is_null());
            Ok(())
        }
    }
}

impl<T> TryMutex<T> for Mutex<T> {
    fn try_new(value: T) -> Result<Mutex<T>, AllocError> {
        // Allocate the backend eagerly, then install the value and activate.
        let uninit = Self::try_new_uninit()?;
        let mut filled = uninit;
        filled.get_mut().unwrap().write(value);
        // SAFETY: we just wrote the data slot above.
        Ok(unsafe { Self::assume_init(filled) })
    }

    fn try_new_give_back(value: T) -> Result<Mutex<T>, (T, AllocError)> {
        // On allocation failure hand the original value back to the caller.
        let uninit = match Self::try_new_uninit() {
            Ok(u) => u,
            Err(e) => return Err((value, e)),
        };
        let mut filled = uninit;
        filled.get_mut().unwrap().write(value);
        // SAFETY: we just wrote the data slot above.
        Ok(unsafe { Self::assume_init(filled) })
    }

    fn try_new_uninit() -> Result<Mutex<MaybeUninit<T>>, AllocError> {
        let this = shell(MaybeUninit::uninit());
        // SAFETY: `this` is a fresh, uniquely-owned shell whose OnceBox slot is
        // null and cannot be observed by any other thread yet. Viewing its
        // leading pointer word as an `AtomicPtr` is sound (layout-identical).
        // On allocation failure the slot is left null, so dropping the shell
        // leaks nothing.
        let slot = unsafe { oncebox_slot(&this) };
        match unsafe { arm_once_box(slot) } {
            Ok(()) => Ok(this),
            Err(e) => {
                drop(this);
                Err(e)
            }
        }
    }

    fn try_new_zeroed() -> Result<Mutex<MaybeUninit<T>>, AllocError> {
        let this = shell(MaybeUninit::zeroed());
        // SAFETY: as in `try_new_uninit`.
        let slot = unsafe { oncebox_slot(&this) };
        match unsafe { arm_once_box(slot) } {
            Ok(()) => Ok(this),
            Err(e) => {
                drop(this);
                Err(e)
            }
        }
    }

    unsafe fn assume_init(this: Mutex<MaybeUninit<T>>) -> Mutex<T> {
        unsafe { assume_init_impl(this) }
    }

    fn try_arm(&self) -> Result<(), AllocError> {
        // Arming mutates only the OnceBox pointer cell, which is interior-
        // mutable (an atomic), so a shared reference suffices — exactly how
        // std's `OnceBox::get_or_init(&self)` works.
        let slot = unsafe { oncebox_slot(self) };
        // SAFETY: `self` is a valid `Mutex<T>`; arming only touches the leading
        // OnceBox pointer cell through its atomic. If it is already armed this
        // is a no-op.
        unsafe { arm_once_box(slot) }
    }
}

/// Locate the `OnceBox` pointer cell backing a `Mutex<_>`'s pthread backend and
/// view it as an [`lang_core::sync::atomic::AtomicPtr`] so we can perform the
/// load/CAS that std's own `OnceBox::initialize` performs.
///
/// We route through the generated layout mirror first rather than casting the
/// public type straight to a bare pointer: `&Mutex<T>` → `&SysMutexMirror<T>`
/// (layout-identical, exactly what [`shell`](super::shell) relies on) → the
/// real mirror field path `.data.pal.ptr`. Only the final step — viewing the
/// mirror's opaque `Atomic<*mut SysPalMutex>` word as a usable
/// `AtomicPtr<SysPalMutex>` — is a raw reinterpretation, because the mirror's
/// atomic stub exposes no operations. That keeps every intermediate hop anchored
/// in the actual generated struct layout instead of an unstated offset guess.
///
/// # Safety
///
/// The caller must hold a reference to a valid `Mutex<_>` whose `OnceBox`
/// pointer cell is not aliased by any non-atomic access. Both `try_new*`
/// (unique ownership of a fresh shell) and `try_arm` (shared reference, with all
/// other accesses going through the mutex's own atomics) satisfy this.
unsafe fn oncebox_slot<T>(this: &Mutex<T>) -> &lang_core::sync::atomic::AtomicPtr<PalMutex> {
    use super::SysMutexMirror;

    // Step 1: public `Mutex<T>` → its layout mirror. Identical field layout
    // (both generated from the same std source), so reinterpreting the shared
    // reference is sound. Proven by the size/alignment assertion below.
    assert_layout::<&Mutex<T>, &SysMutexMirror<T>>();
    let mirror: &SysMutexMirror<T> = unsafe { mem::transmute(this) };

    // Step 2: walk the real mirror fields down to the OnceBox pointer cell. The
    // mirror types this as `*mut SysPalMutex`; our [`PalMutex`] is
    // layout-identical, so we read the same word as `*mut PalMutex`.
    let slot_cell: &rustyfill_sys::std::sync::atomic::Atomic<*mut SysPalMutex> =
        &mirror.inner.pal.ptr;

    // Step 3: the mirror's atomic is a repr(transparent) wrapper over
    // `UnsafeCell<*mut _>` — layout-identical to `AtomicPtr<_>` (a single
    // machine-width pointer). Reinterpret the shared reference as a real
    // `AtomicPtr<PalMutex>` so we can call its atomic methods.
    assert_layout::<
        &rustyfill_sys::std::sync::atomic::Atomic<*mut SysPalMutex>,
        &lang_core::sync::atomic::AtomicPtr<PalMutex>,
    >();
    unsafe { mem::transmute(slot_cell) }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Layout parity between our Rust-side [`PalMutex`] and the generated
    /// [`SysPalMutex`] mirror is what lets us publish one where the other is
    /// expected. Guard it explicitly.
    #[test]
    fn pal_mutex_layout_matches_mirror() {
        use lang_core::mem::{align_of, size_of};
        assert_eq!(size_of::<PalMutex>(), size_of::<SysPalMutex>());
        assert_eq!(align_of::<PalMutex>(), align_of::<SysPalMutex>());
    }

    /// A pinned `PalMutex` must initialise, be usable for a lock/unlock cycle,
    /// and destroy cleanly — exercising the full pinning discipline on a real
    /// pthread target.
    #[test]
    fn pal_mutex_init_use_destroy_roundtrip() {
        use lang_alloc::boxed::Box;
        let mut pinned = Box::pin(PalMutex::new());
        // SAFETY: freshly allocated, not yet initialised, at a stable address.
        unsafe { pinned.as_mut().init() };

        // Lock and unlock through the raw handle to prove the mutex is live.
        // SAFETY: the mutex was just initialised and is currently unlocked.
        unsafe {
            let rc = libc::pthread_mutex_lock(pinned.raw());
            assert_eq!(rc, 0);
            let rc = libc::pthread_mutex_unlock(pinned.raw());
            assert_eq!(rc, 0);
        }

        // SAFETY: unlocked and at its original address.
        unsafe { pinned.as_ref().destroy() };
    }
}
