//! Fallible cloning for types that may require heap allocation.
//!
//! Provides the [`TryClone`] trait, a drop-in analogue of [`Clone`] that can
//! fail when the clone operation requires allocating memory (e.g. cloning a
//! [`String`] or [`Vec`]).
//!
//! # Design
//!
//! `TryClone` requires [`Clone`] as a supertrait. Types implement it individually.
//! Each implementation must itself only call other fallible operations so that
//! `try_clone` never panics.
//!
//! All well-known [`Copy`] types (numbers, booleans, characters, unit type,
//! tuples, and arrays) are implemented explicitly below. Non-`Copy` compound
//! types ([`Option`], [`Result`]) delegate to their inner values via `TryClone`.
//!
//! Structs can derive `TryClone` via the [`rustyfill_macros::TryClone`] proc macro,
//! which requires every field to also implement `TryClone`.

use crate::alloc::{AllocError, TryReserveError};
use core::clone::Clone;
use core::fmt;

/// Returned when a fallible clone operation fails.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TryCloneError {
    /// A raw heap allocation failed (no collection involved).
    Alloc(AllocError),
    /// A capacity reservation on a collection failed (overflow or OOM).
    Reserve(TryReserveError),
    /// A manually detected arithmetic overflow (e.g., size multiplication).
    Overflow,
    /// A logic-level failure with a static diagnostic message.
    Other(&'static str),
}

impl fmt::Display for TryCloneError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Alloc(_) => write!(f, "clone failed: heap allocation error"),
            Self::Reserve(e) => write!(f, "clone failed: {}", e),
            Self::Overflow => write!(f, "clone failed: capacity calculation overflowed"),
            Self::Other(msg) => write!(f, "clone failed: {}", msg),
        }
    }
}

impl From<AllocError> for TryCloneError {
    fn from(e: AllocError) -> Self {
        Self::Alloc(e)
    }
}

impl From<TryReserveError> for TryCloneError {
    fn from(err: TryReserveError) -> Self {
        Self::Reserve(err)
    }
}

/// A fallible analogue of [`Clone`].
///
/// Unlike [`Clone`], which panics on allocation failure, [`TryClone`] returns
/// a [`Result`] so callers can handle out-of-memory gracefully.
///
/// Implementors must ensure that `try_clone` never panics — inner values should
/// also be cloned via [`TryClone`] rather than [`Clone`].
///
/// # Laziness
///
/// If cloning requires allocating memory (e.g. growing a buffer), reserve the
/// backing storage **before** performing any logical work such as recursively
/// cloning inner fields if possible. This way an allocation failure short‑circuits
/// early and avoids wasted computation or intermediate values. See
/// [`Box<T>`](crate::boxed::TryBox) for an example of this pattern.
pub trait TryClone: Clone {
    /// Attempt to clone `self`.
    fn try_clone(&self) -> Result<Self, TryCloneError>;
}

// ── Macro helpers ──────────────────────────────────────────────────────────────

/// Implements `TryClone` infallibly for a list of `Copy` types.
macro_rules! impl_try_clone_copy {
    ($($t:ty),* $(,)?) => {
        $(
            impl TryClone for $t {
                #[inline]
                fn try_clone(&self) -> Result<Self, TryCloneError> {
                    Ok(*self)
                }
            }
        )*
    };
}

// ── Numeric primitives ─────────────────────────────────────────────────────────

// Unsigned integers
impl_try_clone_copy!(u8, u16, u32, u64, u128, usize);

// Signed integers
impl_try_clone_copy!(i8, i16, i32, i64, i128, isize);

// Floating point
impl_try_clone_copy!(f32, f64);

// ── Other Copy primitives ──────────────────────────────────────────────────────

impl_try_clone_copy!(bool, char, ());

// ── Tuple implementations (generated by proc-macro) ────────────────────────────

rustyfill_macros::try_clone_tuples!(12);

// ── Arrays [T; N] ──────────────────────────────────────────────────────────────

/// Panic-safe guard that drops any initialized elements in a `MaybeUninit` array
/// if dropped before `forget()` is called (e.g. on panic or early return).
struct ArrayInitGuard<'a, T, const N: usize> {
    slots: &'a mut [core::mem::MaybeUninit<T>; N],
    count: usize,
}

impl<'a, T, const N: usize> ArrayInitGuard<'a, T, N> {
    fn new(slots: &'a mut [core::mem::MaybeUninit<T>; N]) -> Self {
        Self { slots, count: 0 }
    }

    /// Disable the guard's Drop so that it no longer cleans up on scope exit.
    /// Call this only after all slots have been successfully initialized.
    fn forget(mut self) {
        self.count = 0;
        core::mem::forget(self);
    }
}

impl<'a, T, const N: usize> Drop for ArrayInitGuard<'a, T, N> {
    fn drop(&mut self) {
        unsafe {
            for slot in self.slots.iter_mut().take(self.count) {
                core::ptr::drop_in_place(slot.as_mut_ptr());
            }
        }
    }
}

impl<T: TryClone, const N: usize> TryClone for [T; N] {
    fn try_clone(&self) -> Result<Self, TryCloneError> {
        let mut out: [core::mem::MaybeUninit<T>; N] =
            core::array::from_fn(|_| core::mem::MaybeUninit::uninit());
        let mut guard = ArrayInitGuard::new(&mut out);

        for (i, elem) in self.iter().enumerate() {
            match elem.try_clone() {
                Ok(cloned) => {
                    unsafe {
                        core::ptr::write(guard.slots[i].as_mut_ptr(), cloned);
                    }
                    guard.count += 1;
                }
                Err(e) => {
                    // Guard's Drop cleans up whatever was written so far.
                    return Err(e);
                }
            }
        }

        guard.forget();
        // SAFETY: we verified that all N slots were written successfully above.
        // Using transmute_copy instead of MaybeUninit::array_assume_init because
        // the latter is still unstable as of Rust 1.97 (tracking issue #96097).
        Ok(unsafe { core::mem::transmute_copy(&out) })
    }
}

// ── Slice references ───────────────────────────────────────────────────────────
// Immutable references to slices are just pointer copies — no allocation needed,
// so these are infallible. The Clone supertrait is satisfied because &[T] and
// &str both implement Clone (via Copy) in std.
//
// Note: &mut [T] and &mut str do NOT implement Clone in std, so they cannot
// satisfy the Clone supertrait bound on TryClone. They are intentionally omitted.

impl<T> TryClone for &[T] {
    #[inline]
    fn try_clone(&self) -> Result<Self, TryCloneError> {
        Ok(*self)
    }
}

impl TryClone for &str {
    #[inline]
    fn try_clone(&self) -> Result<Self, TryCloneError> {
        Ok(*self)
    }
}

// ── Option ─────────────────────────────────────────────────────────────────────

impl<T: TryClone> TryClone for Option<T> {
    fn try_clone(&self) -> Result<Self, TryCloneError> {
        match self {
            Some(v) => Ok(Some(v.try_clone()?)),
            None => Ok(None),
        }
    }
}

// ── Result ─────────────────────────────────────────────────────────────────────

impl<T: TryClone, E: TryClone> TryClone for Result<T, E> {
    fn try_clone(&self) -> Result<Self, TryCloneError> {
        match self {
            Ok(v) => Ok(Ok(v.try_clone()?)),
            Err(e) => Ok(Err(e.try_clone()?)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Unsigned integers ──────────────────────────────────────────────────────

    #[test]
    fn u8_try_clone() {
        assert_eq!((42u8).try_clone().unwrap(), 42);
    }

    #[test]
    fn u16_try_clone() {
        assert_eq!((0xCAFE_u16).try_clone().unwrap(), 0xCAFE);
    }

    #[test]
    fn u32_try_clone() {
        assert_eq!((0xDEADBEEF_u32).try_clone().unwrap(), 0xDEADBEEF);
    }

    #[test]
    fn u64_try_clone() {
        assert_eq!(
            (0xCAFEBABE_DEADBEEF_u64).try_clone().unwrap(),
            0xCAFEBABE_DEADBEEF
        );
    }

    #[test]
    fn u128_try_clone() {
        let v = u128::MAX;
        assert_eq!(v.try_clone().unwrap(), v);
    }

    #[test]
    fn usize_try_clone() {
        assert_eq!((99_usize).try_clone().unwrap(), 99);
    }

    // ── Signed integers ────────────────────────────────────────────────────────

    #[test]
    fn i8_try_clone() {
        assert_eq!((-42i8).try_clone().unwrap(), -42);
    }

    #[test]
    fn i16_try_clone() {
        assert_eq!((-0x7FFE_i16).try_clone().unwrap(), -0x7FFE);
    }

    #[test]
    fn i32_try_clone() {
        assert_eq!(i32::MIN.try_clone().unwrap(), i32::MIN);
    }

    #[test]
    fn i64_try_clone() {
        assert_eq!(i64::MAX.try_clone().unwrap(), i64::MAX);
    }

    #[test]
    fn i128_try_clone() {
        assert_eq!(i128::MIN.try_clone().unwrap(), i128::MIN);
    }

    #[test]
    fn isize_try_clone() {
        assert_eq!((-1_isize).try_clone().unwrap(), -1);
    }

    // ── Floating point ─────────────────────────────────────────────────────────

    #[test]
    fn f32_try_clone() {
        assert_eq!(
            (std::f32::consts::E).try_clone().unwrap(),
            std::f32::consts::E
        );
    }

    #[test]
    fn f64_try_clone() {
        assert_eq!(
            (std::f64::consts::PI).try_clone().unwrap(),
            std::f64::consts::PI
        );
    }

    // ── Other Copy primitives ──────────────────────────────────────────────────

    #[test]
    fn bool_try_clone_true() {
        assert!(true.try_clone().unwrap());
    }

    #[test]
    fn bool_try_clone_false() {
        assert!(!false.try_clone().unwrap());
    }

    #[test]
    fn char_try_clone() {
        assert_eq!('🦀'.try_clone().unwrap(), '🦀');
    }

    #[test]
    fn unit_try_clone() {
        assert_eq!(().try_clone().unwrap(), ());
    }

    // ── Tuples ─────────────────────────────────────────────────────────────────

    #[test]
    fn tuple_1_try_clone() {
        let t = (42u8,);
        assert_eq!(t.try_clone().unwrap(), (42u8,));
    }

    #[test]
    fn tuple_2_try_clone() {
        let t = (1u8, 2u16);
        assert_eq!(t.try_clone().unwrap(), (1u8, 2u16));
    }

    #[test]
    fn tuple_3_try_clone() {
        let t = (true, 'a', 3u32);
        assert_eq!(t.try_clone().unwrap(), (true, 'a', 3u32));
    }

    #[test]
    fn tuple_nested_try_clone() {
        let t: ((u8, bool), i32) = ((1, true), -5);
        assert_eq!(t.try_clone().unwrap(), ((1, true), -5));
    }

    // ── Arrays ─────────────────────────────────────────────────────────────────

    #[test]
    fn array_empty_try_clone() {
        let a: [u8; 0] = [];
        assert_eq!(a.try_clone().unwrap(), []);
    }

    #[test]
    fn array_primitive_try_clone() {
        let a = [1u8, 2, 3, 4];
        assert_eq!(a.try_clone().unwrap(), [1, 2, 3, 4]);
    }

    #[test]
    fn array_of_tuples_try_clone() {
        let a = [(1u8, true), (2u8, false)];
        assert_eq!(a.try_clone().unwrap(), [(1, true), (2, false)]);
    }

    // ── Option ─────────────────────────────────────────────────────────────────

    #[test]
    fn option_some_try_clone() {
        let o: Option<u8> = Some(42);
        assert_eq!(o.try_clone().unwrap(), Some(42));
    }

    #[test]
    fn option_none_try_clone() {
        let o: Option<i32> = None;
        assert_eq!(o.try_clone().unwrap(), None);
    }

    #[test]
    fn option_nested_try_clone() {
        let o: Option<Option<bool>> = Some(Some(true));
        assert_eq!(o.try_clone().unwrap(), Some(Some(true)));
    }

    // ── Result ─────────────────────────────────────────────────────────────────

    #[test]
    fn result_ok_try_clone() {
        let r: Result<u8, i32> = Ok(42);
        assert_eq!(r.try_clone().unwrap(), Ok(42));
    }

    #[test]
    fn result_err_try_clone() {
        let r: Result<u8, i32> = Err(-99);
        assert_eq!(r.try_clone().unwrap(), Err(-99));
    }

    #[test]
    fn result_nested_try_clone() {
        let r: Result<Result<bool, u8>, i32> = Ok(Ok(true));
        assert_eq!(r.try_clone().unwrap(), Ok(Ok(true)));
    }

    // ── Compound nesting ───────────────────────────────────────────────────────

    #[test]
    fn option_result_array_try_clone() {
        let o: Option<Result<[u8; 3], bool>> = Some(Ok([1, 2, 3]));
        assert_eq!(o.try_clone().unwrap(), Some(Ok([1, 2, 3])));
    }

    #[test]
    fn tuple_option_result_try_clone() {
        let t: (Option<u8>, Result<bool, i16>) = (Some(7), Ok(false));
        assert_eq!(t.try_clone().unwrap(), (Some(7), Ok(false)));
    }

    // ── Enum TryClone ──────────────────────────────────────────────────────────

    mod enum_tests {
        use super::super::{TryClone, TryCloneError};

        // Unit variants
        #[derive(Debug, Clone, PartialEq, Eq)]
        enum Color {
            Red,
            #[allow(unused)]
            Green,
            Blue,
        }

        impl TryClone for Color {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Color::Red => Ok(Color::Red),
                    Color::Green => Ok(Color::Green),
                    Color::Blue => Ok(Color::Blue),
                }
            }
        }

        #[test]
        fn unit_enum_try_clone_red() {
            assert_eq!(Color::Red.try_clone().unwrap(), Color::Red);
        }

        #[test]
        fn unit_enum_try_clone_blue() {
            assert_eq!(Color::Blue.try_clone().unwrap(), Color::Blue);
        }

        // Named fields
        #[derive(Debug, Clone, PartialEq)]
        enum Shape {
            Circle { radius: u32 },
            Rectangle { width: u32, height: u32 },
            Empty {},
        }

        impl TryClone for Shape {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Shape::Circle { radius } => Ok(Shape::Circle {
                        radius: (*radius).try_clone()?,
                    }),
                    Shape::Rectangle { width, height } => Ok(Shape::Rectangle {
                        width: (*width).try_clone()?,
                        height: (*height).try_clone()?,
                    }),
                    Shape::Empty {} => Ok(Shape::Empty {}),
                }
            }
        }

        #[test]
        fn named_enum_circle_try_clone() {
            let s = Shape::Circle { radius: 5 };
            assert_eq!(s.try_clone().unwrap(), Shape::Circle { radius: 5 });
        }

        #[test]
        fn named_enum_rectangle_try_clone() {
            let s = Shape::Rectangle {
                width: 3,
                height: 4,
            };
            assert_eq!(
                s.try_clone().unwrap(),
                Shape::Rectangle {
                    width: 3,
                    height: 4
                }
            );
        }

        #[test]
        fn named_enum_empty_try_clone() {
            let s = Shape::Empty {};
            assert_eq!(s.try_clone().unwrap(), Shape::Empty {});
        }

        // Unnamed (tuple) fields
        #[derive(Debug, Clone, PartialEq)]
        enum Message {
            Text(u32),
            Pair(u32, bool),
            None,
        }

        impl TryClone for Message {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Message::Text(f0) => Ok(Message::Text((*f0).try_clone()?)),
                    Message::Pair(f0, f1) => {
                        Ok(Message::Pair((*f0).try_clone()?, (*f1).try_clone()?))
                    }
                    Message::None => Ok(Message::None),
                }
            }
        }

        #[test]
        fn unnamed_enum_single_field_try_clone() {
            let m = Message::Text(42);
            assert_eq!(m.try_clone().unwrap(), Message::Text(42));
        }

        #[test]
        fn unnamed_enum_multi_field_try_clone() {
            let m = Message::Pair(7, true);
            assert_eq!(m.try_clone().unwrap(), Message::Pair(7, true));
        }

        #[test]
        fn unnamed_enum_unit_try_clone() {
            let m = Message::None;
            assert_eq!(m.try_clone().unwrap(), Message::None);
        }

        // Mixed variants
        #[derive(Debug, Clone, PartialEq)]
        enum Mixed {
            A,
            B(u8),
            C { val: i32 },
            D(bool, char),
        }

        impl TryClone for Mixed {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Mixed::A => Ok(Mixed::A),
                    Mixed::B(f0) => Ok(Mixed::B((*f0).try_clone()?)),
                    Mixed::C { val } => Ok(Mixed::C {
                        val: (*val).try_clone()?,
                    }),
                    Mixed::D(f0, f1) => Ok(Mixed::D((*f0).try_clone()?, (*f1).try_clone()?)),
                }
            }
        }

        #[test]
        fn mixed_enum_all_variants_try_clone() {
            assert_eq!(Mixed::A.try_clone().unwrap(), Mixed::A);
            assert_eq!(Mixed::B(99).try_clone().unwrap(), Mixed::B(99));
            assert_eq!(
                Mixed::C { val: -1 }.try_clone().unwrap(),
                Mixed::C { val: -1 }
            );
            assert_eq!(
                Mixed::D(true, 'x').try_clone().unwrap(),
                Mixed::D(true, 'x')
            );
        }

        // Nested enums
        #[derive(Debug, Clone, PartialEq)]
        enum Inner {
            X(u8),
            #[allow(unused)]
            Y,
        }

        impl TryClone for Inner {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Inner::X(f0) => Ok(Inner::X((*f0).try_clone()?)),
                    Inner::Y => Ok(Inner::Y),
                }
            }
        }

        #[derive(Debug, Clone, PartialEq)]
        enum Outer {
            Contains(Inner),
            Value(i32),
        }

        impl TryClone for Outer {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Outer::Contains(f0) => Ok(Outer::Contains(f0.try_clone()?)),
                    Outer::Value(f0) => Ok(Outer::Value((*f0).try_clone()?)),
                }
            }
        }

        #[test]
        fn nested_enum_try_clone() {
            let outer = Outer::Contains(Inner::X(42));
            assert_eq!(outer.try_clone().unwrap(), Outer::Contains(Inner::X(42)));

            let outer2 = Outer::Value(-5);
            assert_eq!(outer2.try_clone().unwrap(), Outer::Value(-5));
        }

        // Generic enum
        #[derive(Debug, Clone, PartialEq)]
        enum Maybe<T> {
            Just(T),
            Nothing,
        }

        impl<T: TryClone> TryClone for Maybe<T> {
            fn try_clone(&self) -> Result<Self, TryCloneError> {
                match self {
                    Maybe::Just(f0) => Ok(Maybe::Just(f0.try_clone()?)),
                    Maybe::Nothing => Ok(Maybe::Nothing),
                }
            }
        }

        #[test]
        fn generic_enum_just_try_clone() {
            let m: Maybe<u32> = Maybe::Just(100);
            assert_eq!(m.try_clone().unwrap(), Maybe::Just(100));
        }

        #[test]
        fn generic_enum_nothing_try_clone() {
            let m: Maybe<i16> = Maybe::Nothing;
            assert_eq!(m.try_clone().unwrap(), Maybe::Nothing);
        }
    }

    // ── Slice references ───────────────────────────────────────────────────────

    #[test]
    fn slice_ref_try_clone() {
        let data = [1u32, 2, 3];
        let slice: &[u32] = &data;
        let cloned: &[u32] = slice.try_clone().unwrap();
        assert_eq!(cloned, &[1, 2, 3]);
    }

    #[test]
    fn slice_ref_empty_try_clone() {
        let data: [u8; 0] = [];
        let slice: &[u8] = &data;
        let cloned: &[u8] = slice.try_clone().unwrap();
        assert!(cloned.is_empty());
    }

    #[test]
    fn str_ref_try_clone() {
        let s = "hello world";
        let cloned: &str = s.try_clone().unwrap();
        assert_eq!(cloned, "hello world");
    }

    #[test]
    fn str_ref_empty_try_clone() {
        let s = "";
        let cloned: &str = s.try_clone().unwrap();
        assert_eq!(cloned, "");
    }

    #[test]
    fn str_ref_unicode_try_clone() {
        let s = "🦀 Rust 🚀";
        let cloned: &str = s.try_clone().unwrap();
        assert_eq!(cloned, "🦀 Rust 🚀");
    }
}
