//! Fallible default construction for types that may require heap allocation.
//!
//! Provides the [`TryDefault`] trait, a drop-in analogue of [`Default`] that can
//! fail when the default value requires allocating memory (e.g. constructing a
//! default [`String`] or [`Vec`]).
//!
//! # Design
//!
//! `TryDefault` requires [`Default`] as a supertrait. Types implement it individually.
//! Each implementation must itself only call other fallible operations so that
//! `try_default` never panics.
//!
//! All well-known [`Copy`] types (numbers, booleans, characters, unit type,
//! tuples, and arrays) are implemented explicitly below. Non-`Copy` compound
//! types ([`Option`], [`Result`]) delegate to their inner values via `TryDefault`.
//!
//! Structs and enums can derive `TryDefault` via the [`fallibles_macros::TryDefault`]
//! proc macro, which requires every field in every variant to also implement `TryDefault`.

use crate::alloc::AllocError;
use core::fmt;

/// Returned when a fallible default construction fails.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TryDefaultError {
    /// A raw heap allocation failed (no collection involved).
    Alloc(AllocError),
    /// A capacity reservation on a collection failed (overflow or OOM).
    Reserve(std::collections::TryReserveError),
    /// A manually detected arithmetic overflow (e.g., size multiplication).
    Overflow,
    /// A logic-level failure with a static diagnostic message.
    Other(&'static str),
}

impl fmt::Display for TryDefaultError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Alloc(_) => write!(f, "default failed: heap allocation error"),
            Self::Reserve(e) => write!(f, "default failed: {}", e),
            Self::Overflow => write!(f, "default failed: capacity calculation overflowed"),
            Self::Other(msg) => write!(f, "default failed: {}", msg),
        }
    }
}

impl From<AllocError> for TryDefaultError {
    fn from(_: AllocError) -> Self {
        Self::Alloc(AllocError)
    }
}

impl From<std::collections::TryReserveError> for TryDefaultError {
    fn from(err: std::collections::TryReserveError) -> Self {
        Self::Reserve(err)
    }
}

/// A fallible analogue of [`core::default::Default`].
///
/// Unlike [`core::default::Default`], which panics on allocation failure,
/// [`TryDefault`] returns a [`Result`] so callers can handle out-of-memory
/// gracefully.
///
/// Implementors must ensure that `try_default` never panics — inner values should
/// also be constructed via [`TryDefault`] rather than [`core::default::Default`].
///
/// # Laziness
///
/// If constructing the default value requires allocating memory (e.g. reserving
/// capacity for a vector), reserve the backing storage **before** performing any
/// logical work such as recursively building inner fields. This way an allocation
/// failure short‑circuits early and avoids wasted computation or partially
/// constructed intermediate values. See
/// [`Box<T>`](crate::boxed::TryBox) for an example of this pattern.
pub trait TryDefault {
    /// Attempt to construct the default value.
    fn try_default() -> Result<Self, TryDefaultError>
    where
        Self: Sized;
}

// ── Macro helpers ──────────────────────────────────────────────────────────────

/// Implements `TryDefault` infallibly for a list of `Copy` types.
macro_rules! impl_try_default_copy {
    ($($t:ty),* $(,)?) => {
        $(
            impl TryDefault for $t {
                #[inline]
                fn try_default() -> Result<Self, TryDefaultError> {
                    Ok(Default::default())
                }
            }
        )*
    };
}

// ── Numeric primitives ─────────────────────────────────────────────────────────

// Unsigned integers
impl_try_default_copy!(u8, u16, u32, u64, u128, usize);

// Signed integers
impl_try_default_copy!(i8, i16, i32, i64, i128, isize);

// Floating point
impl_try_default_copy!(f32, f64);

// ── Other Copy primitives ──────────────────────────────────────────────────────

impl_try_default_copy!(bool, char, ());

// ── Tuple implementations (generated by proc-macro) ────────────────────────────

fallibles_macros::try_default_tuples!(12);

// ── Arrays [T; N] ──────────────────────────────────────────────────────────────

impl<T: TryDefault, const N: usize> TryDefault for [T; N] {
    
    fn try_default() -> Result<Self, TryDefaultError> {
        let mut out: [core::mem::MaybeUninit<T>; N] =
            core::array::from_fn(|_| core::mem::MaybeUninit::uninit());
        let mut initialized = 0usize;

        for slot in out.iter_mut() {
            match T::try_default() {
                Ok(val) => {
                    unsafe {
                        core::ptr::write(slot.as_mut_ptr(), val);
                    }
                    initialized += 1;
                }
                Err(e) => {
                    // Drop every item we already wrote to avoid leaking.
                    unsafe {
                        for done in out.iter_mut().take(initialized) {
                            core::ptr::drop_in_place(done.as_mut_ptr());
                        }
                    }
                    return Err(e);
                }
            }
        }

        // SAFETY: we verified that all N slots were written successfully.
        Ok(unsafe { core::mem::transmute_copy(&out) })
    }
}

// ── Option ─────────────────────────────────────────────────────────────────────

impl<T: TryDefault> TryDefault for Option<T> {
    
    fn try_default() -> Result<Self, TryDefaultError> {
        Ok(None)
    }
}

// ── Result ─────────────────────────────────────────────────────────────────────

impl<T: TryDefault, E: TryDefault> TryDefault for Result<T, E> {
    
    fn try_default() -> Result<Self, TryDefaultError> {
        Ok(Ok(T::try_default()?))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Unsigned integers ──────────────────────────────────────────────────────

    #[test]
    fn u8_try_default() {
        assert_eq!(u8::try_default().unwrap(), 0);
    }

    #[test]
    fn u16_try_default() {
        assert_eq!(u16::try_default().unwrap(), 0);
    }

    #[test]
    fn u32_try_default() {
        assert_eq!(u32::try_default().unwrap(), 0);
    }

    #[test]
    fn u64_try_default() {
        assert_eq!(u64::try_default().unwrap(), 0);
    }

    #[test]
    fn u128_try_default() {
        assert_eq!(u128::try_default().unwrap(), 0);
    }

    #[test]
    fn usize_try_default() {
        assert_eq!(usize::try_default().unwrap(), 0);
    }

    // ── Signed integers ────────────────────────────────────────────────────────

    #[test]
    fn i8_try_default() {
        assert_eq!(i8::try_default().unwrap(), 0);
    }

    #[test]
    fn i16_try_default() {
        assert_eq!(i16::try_default().unwrap(), 0);
    }

    #[test]
    fn i32_try_default() {
        assert_eq!(i32::try_default().unwrap(), 0);
    }

    #[test]
    fn i64_try_default() {
        assert_eq!(i64::try_default().unwrap(), 0);
    }

    #[test]
    fn i128_try_default() {
        assert_eq!(i128::try_default().unwrap(), 0);
    }

    #[test]
    fn isize_try_default() {
        assert_eq!(isize::try_default().unwrap(), 0);
    }

    // ── Floating point ─────────────────────────────────────────────────────────

    #[test]
    fn f32_try_default() {
        assert_eq!(f32::try_default().unwrap(), 0.0);
    }

    #[test]
    fn f64_try_default() {
        assert_eq!(f64::try_default().unwrap(), 0.0);
    }

    // ── Other Copy primitives ──────────────────────────────────────────────────

    #[test]
    fn bool_try_default() {
        assert!(!bool::try_default().unwrap());
    }

    #[test]
    fn char_try_default() {
        assert_eq!(char::try_default().unwrap(), '\0');
    }

    #[test]
    fn unit_try_default() {
        let _: () = <() as TryDefault>::try_default().unwrap();
    }

    // ── Tuples ─────────────────────────────────────────────────────────────────

    #[test]
    fn tuple_1_try_default() {
        let t = (0u8,);
        assert_eq!(<(u8,)>::try_default().unwrap(), t);
    }

    #[test]
    fn tuple_2_try_default() {
        assert_eq!(<(u8, u16)>::try_default().unwrap(), (0u8, 0u16));
    }

    #[test]
    fn tuple_3_try_default() {
        assert_eq!(
            <(bool, char, u32)>::try_default().unwrap(),
            (false, '\0', 0u32)
        );
    }

    #[test]
    fn tuple_nested_try_default() {
        let expected: ((u8, bool), i32) = ((0, false), 0);
        assert_eq!(<((u8, bool), i32)>::try_default().unwrap(), expected);
    }

    // ── Arrays ─────────────────────────────────────────────────────────────────

    #[test]
    fn array_empty_try_default() {
        let a: [u8; 0] = [];
        assert_eq!(<[u8; 0]>::try_default().unwrap(), a);
    }

    #[test]
    fn array_primitive_try_default() {
        assert_eq!(<[u8; 4]>::try_default().unwrap(), [0, 0, 0, 0]);
    }

    #[test]
    fn array_of_tuples_try_default() {
        assert_eq!(
            <[(u8, bool); 2]>::try_default().unwrap(),
            [(0, false), (0, false)]
        );
    }

    // ── Option ─────────────────────────────────────────────────────────────────

    #[test]
    fn option_some_unit_try_default() {
        assert_eq!(Option::<()>::try_default().unwrap(), None);
    }

    #[test]
    fn option_none_try_default() {
        assert_eq!(Option::<i32>::try_default().unwrap(), None);
    }

    #[test]
    fn option_nested_try_default() {
        assert_eq!(Option::<Option<bool>>::try_default().unwrap(), None);
    }

    // ── Result ─────────────────────────────────────────────────────────────────

    #[test]
    fn result_ok_try_default() {
        let expected: Result<u8, i32> = Ok(0);
        let actual: Result<u8, i32> = TryDefault::try_default().unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn result_err_try_default() {
        // Result's default is Ok(T::default()), even when E has a default.
        let expected: Result<i32, u8> = Ok(0);
        let actual: Result<i32, u8> = TryDefault::try_default().unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn result_nested_try_default() {
        let expected: Result<Result<bool, u8>, i32> = Ok(Ok(false));
        let actual: Result<Result<bool, u8>, i32> = TryDefault::try_default().unwrap();
        assert_eq!(actual, expected);
    }

    // ── Compound nesting ───────────────────────────────────────────────────────

    #[test]
    fn option_result_array_try_default() {
        let expected: Option<Result<[u8; 3], bool>> = None;
        let actual: Option<Result<[u8; 3], bool>> = TryDefault::try_default().unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn tuple_option_result_try_default() {
        let expected: (Option<u8>, Result<bool, i16>) = (None, Ok(false));
        let actual: (Option<u8>, Result<bool, i16>) = <_>::try_default().unwrap();
        assert_eq!(actual, expected);
    }
}
