[package]
name = "rustyfill-sys"
version.workspace = true
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[features]
nightly = []
std = []
drop-annotations = []

[build-dependencies]
rustyfill-sys-bindings = { path = "../rustyfill-sys-bindings" }
syn = { version = "2", features = ["full"] }
